"""検査データの質問を書き出す（W3-c2。期待は人が文書を読んで書いた。読解器・観測器は呼ばない）。出力: questions.jsonl, placement_q.json

truth の欄:
  kind     ONE（充填物 1 つ）・NONE（文書に無い）・SPLIT（充填物 2 つ以上）・YESNO（はい／いいえ疑問）・ILLFORMED（穴 2 つ・印を含む・不定語・AかB）
  fillers  正解の充填物（人が文書から読んだ表記）
  evidence 問いの命題を **その腕のまま** 述べている、既存の読解器 read() が読める文書の文の id（採点は系の引いた文 id の集合とこれの一致を見る）
  extension_support 問いの命題より腕が多い（例: 場所が付く）読める文。正解を支えるが、一致の定義（D9）では証拠にならない
  unread_support    正解を述べているが read() が読めない文（誤答ではなく FALSE_NONE の原因の説明に使う）
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
PL = 'placement_q.json'
rows = []
def q(doc, text, hole, kind, fillers=(), ev=(), ext=(), unread=(), note='', placement=None, direction=''):
    lang = 'en' if doc in ('QD08', 'QD09', 'QD10') else 'ja'
    sid = lambda xs: ['%s-%s' % (doc, x) for x in xs]
    rows.append({'id': 'Q%03d' % (len(rows) + 1), 'doc': doc, 'lang': lang, 'text': text, 'hole': hole,
                 'placement': placement, 'direction': direction,
                 'truth': {'kind': kind, 'fillers': list(fillers), 'evidence': sid(ev), 'extension_support': sid(ext), 'unread_support': sid(unread)},
                 'note': note})
# ---- QD01 学校
q('QD01', '誰が生徒に地図を渡した？', 'PERSON', 'SPLIT', ['先生', '校長'], ['S01', 'S02'], note='充填物が割れる')
q('QD01', '先生は誰に地図を渡した？', 'PERSON', 'ONE', ['生徒'], ['S01'], note='受取人の穴は印では読めない位置')
q('QD01', '誰が本を読む？', 'PERSON', 'ONE', ['先生'], ['S07'], note='非過去')
q('QD01', '誰が鍵を持っている？', 'PERSON', 'NONE', note='文書の疑問文 S05 は証拠ではない')
q('QD01', '誰が先生に手紙を送った？', 'PERSON', 'ONE', ['生徒'], ['S03'])
q('QD01', '誰が生徒に手紙を送った？', 'PERSON', 'NONE', note='S03 は生徒が先生に送った')
q('QD01', '先生は生徒に何を渡した？', 'THING', 'ONE', ['地図'], ['S01'])
q('QD01', '生徒は先生に何を送った？', 'THING', 'ONE', ['手紙'], ['S03'])
q('QD01', '先生は駅で何を渡さなかった？', 'THING', 'ONE', ['地図'], ['S04'], note='否定')
q('QD01', '先生は何を渡さなかった？', 'THING', 'ONE', ['地図'], [], ['S04'], note='場所の腕が多い文だけ')
q('QD01', '先生は何を読んだ？', 'THING', 'NONE', note='S07 は非過去。時制が違う')
q('QD01', '先生は何を読む？', 'THING', 'ONE', ['本'], ['S07'])
q('QD01', '生徒はどこへ行った？', 'PLACE', 'ONE', ['図書館'], ['S06'], note='goal の穴')
q('QD01', '先生はどこで地図を渡さなかった？', 'PLACE', 'ONE', ['駅'], ['S04'], note='place の穴')
q('QD01', 'どんな地図を先生は生徒に渡した？', 'PROPERTY', 'ONE', ['古い'], [], [], ['S08'], note='S08 は地図が古かったと述べる（読解器は読まない）')
q('QD01', 'なぜ先生は駅で地図を渡さなかった？', 'CAUSE', 'NONE')
q('QD01', '先生はどうやって地図を渡した？', 'MANNER', 'NONE')
q('QD01', '先生はいつ地図を渡した？', 'TIME', 'NONE')
q('QD01', '先生は生徒に地図を渡したか？', 'POLAR', 'YESNO')
q('QD01', 'どの人が生徒に地図を渡した？', 'RESTRICTOR', 'SPLIT', ['先生', '校長'], ['S01', 'S02'], placement=PL, note='N=人（PERSON）')
q('QD01', 'どの人間が先生に手紙を送った？', 'RESTRICTOR', 'ONE', ['生徒'], ['S03'], placement=PL, note='N=人間 は配置に無い')
q('QD01', '誰が誰に地図を渡した？', 'ILLFORMED', 'ILLFORMED', note='穴が 2 つ')
q('QD01', '誰かが地図を渡した？', 'ILLFORMED', 'ILLFORMED', note='不定語')
q('QD01', 'Ｘが生徒に地図を渡した？', 'ILLFORMED', 'ILLFORMED', note='印と同じ字を含む質問')
# ---- QD02 駅
q('QD02', '誰が客に切符を渡した？', 'PERSON', 'ONE', ['駅員'], ['S01'], note='否定の S02・非過去の S03 は一致しない')
q('QD02', '誰が客に切符を渡さなかった？', 'PERSON', 'ONE', ['駅員'], ['S02'])
q('QD02', '誰が客に切符を渡す？', 'PERSON', 'ONE', ['運転手'], ['S03'])
q('QD02', '誰が客に車を売った？', 'PERSON', 'ONE', ['社長'], ['S05'], [], ['S09'])
q('QD02', '社長は客に何を売った？', 'THING', 'SPLIT', ['カメラ', '車'], ['S04', 'S05'])
q('QD02', '駅員は客に何を渡した？', 'THING', 'ONE', ['切符'], ['S01'])
q('QD02', '駅員は客に何を渡さなかった？', 'THING', 'ONE', ['切符'], ['S02'])
q('QD02', '客はどこへ行った？', 'PLACE', 'ONE', ['駅'], ['S06'])
q('QD02', '客はいつ駅へ行った？', 'TIME', 'NONE')
q('QD02', 'なぜ駅員は客に切符を渡した？', 'CAUSE', 'ONE', ['客は急いでいた'], [], [], ['S08'], note='S08 が理由を述べる（読解器は読まない）')
q('QD02', 'なぜ社長は客にカメラを売った？', 'CAUSE', 'NONE')
q('QD02', '社長はどうやって客に車を売った？', 'MANNER', 'ONE', ['笑顔で'], [], [], ['S09'])
q('QD02', 'どの人が客に切符を渡した？', 'RESTRICTOR', 'ONE', ['駅員'], ['S01'], placement=PL)
q('QD02', 'どの人が客に車を売った？', 'RESTRICTOR', 'ONE', ['社長'], ['S05'], [], ['S09'], placement=PL)
q('QD02', '社長は客にどの物を売った？', 'RESTRICTOR', 'SPLIT', ['カメラ', '車'], ['S04', 'S05'], placement=PL, note='N=物（ARTIFACT）')
q('QD02', 'どんな切符を駅員は客に渡した？', 'PROPERTY', 'NONE')
q('QD02', '駅員は客に切符を渡さなかったか？', 'POLAR', 'YESNO')
q('QD02', '誰がどこへ行った？', 'ILLFORMED', 'ILLFORMED', note='穴が 2 つ')
# ---- QD03 全角半角・印
q('QD03', '誰が生徒に地図を渡した？', 'PERSON', 'SPLIT', ['A社', 'Ｘ'], ['S03', 'S04', 'S05'], note='Ａ社とA社は NFKC で同じ。Ｘは印と同じ字の正しい充填物')
q('QD03', '誰が兄に本を貸した？', 'PERSON', 'ONE', ['弟'], ['S06'])
q('QD03', '誰が弟に本を貸した？', 'PERSON', 'ONE', ['兄'], ['S07'])
q('QD03', '先生は生徒に何を貸した？', 'THING', 'ONE', ['PC'], ['S01', 'S02'], note='ＰＣとPC は NFKC で同じ')
q('QD03', 'Ａ社は生徒に何を渡した？', 'THING', 'ONE', ['地図'], ['S03', 'S04'], note='非穴の腕の NFKC')
q('QD03', '弟は兄に何を貸した？', 'THING', 'ONE', ['本'], ['S06'])
q('QD03', '弟はいつ兄に本を貸した？', 'TIME', 'NONE')
q('QD03', '先生は生徒にどの物を貸した？', 'RESTRICTOR', 'ONE', ['PC'], ['S01', 'S02'], placement=PL)
q('QD03', 'Ａ社はどこから地図を渡した？', 'PLACE', 'NONE')
q('QD03', '誰がＸに地図を渡した？', 'ILLFORMED', 'ILLFORMED', note='印と同じ字を含む質問')
q('QD03', 'Ｘは生徒に何を渡した？', 'THING', 'ONE', ['地図'], ['S05'], note='印と同じ字を含む質問は棄権する（既知の穴）')
# ---- QD04 職人
q('QD04', '誰が絵を描いた？', 'PERSON', 'ONE', ['画家'], ['S01'], ['S02'], note='腕の多い S02 は同じ充填物')
q('QD04', '誰が網を作った？', 'PERSON', 'ONE', ['漁師'], ['S03'])
q('QD04', '誰が歌を歌った？', 'PERSON', 'ONE', ['歌手'], ['S07'], [], ['S08'])
q('QD04', '誰が家を建てた？', 'PERSON', 'ONE', ['大工'], [], [], ['S09'], note='文が読めない')
q('QD04', '画家は何を描いた？', 'THING', 'ONE', ['絵'], ['S01'])
q('QD04', '漁師は何を送った？', 'THING', 'ONE', ['魚'], [], ['S04'], note='起点の腕が多い文だけ')
q('QD04', '農夫は市場で何を売った？', 'THING', 'ONE', ['馬'], ['S05'])
q('QD04', '歌手は何を歌った？', 'THING', 'ONE', ['歌'], ['S07'])
q('QD04', '漁師はどこから魚を送った？', 'PLACE', 'ONE', ['港'], ['S04'])
q('QD04', '画家はどこで絵を描いた？', 'PLACE', 'ONE', ['寺'], ['S02'], note='place の穴')
q('QD04', '画家はいつ絵を描いた？', 'TIME', 'NONE')
q('QD04', 'なぜ画家は絵を描いた？', 'CAUSE', 'NONE')
q('QD04', '漁師はどうやって網を作った？', 'MANNER', 'NONE')
q('QD04', 'どの人が網を作った？', 'RESTRICTOR', 'ONE', ['漁師'], ['S03'], placement=PL)
q('QD04', 'どの人が絵を描いた？', 'RESTRICTOR', 'ONE', ['画家'], ['S01'], ['S02'], placement=PL, note='画家は配置に無い（型を確かめられない）')
q('QD04', '農夫は粉屋に馬を売ったか？', 'POLAR', 'YESNO')
q('QD04', 'どんな絵を画家は描いた？', 'PROPERTY', 'NONE')
# ---- QD05 時
q('QD05', '先生はいつ本を読んだ？', 'TIME', 'SPLIT', ['朝', '夜'], ['S01', 'S02'])
q('QD05', '先生はいつ来た？', 'TIME', 'ONE', ['三時'], ['S05'])
q('QD05', '先生はいつ地図を渡した？', 'TIME', 'ONE', ['月曜日'], ['S04'])
q('QD05', '看護師はいつ薬を渡した？', 'TIME', 'ONE', ['朝'], ['S03'])
q('QD05', '母はいつ料理を作った？', 'TIME', 'NONE', note='S06 に時は無い')
q('QD05', '兄はいつ新聞を買う？', 'TIME', 'NONE')
q('QD05', '先生はいつ手紙を書いた？', 'TIME', 'NONE', note='昨日手紙を書いたのは父')
q('QD05', '父はいつ手紙を書いた？', 'TIME', 'ONE', ['昨日'], [], [], ['S10'], note='文が読めない')
q('QD05', '先生は朝に何を読んだ？', 'THING', 'ONE', ['本'], ['S01'])
q('QD05', '母は何を作りました？', 'THING', 'ONE', ['弁当'], ['S07'], note='丁寧体')
q('QD05', '母は台所で何を作った？', 'THING', 'ONE', ['料理'], ['S06'])
q('QD05', '姉は店で何を買った？', 'THING', 'ONE', ['服'], ['S08'])
q('QD05', '兄は何を買う？', 'THING', 'ONE', ['新聞'], ['S09'])
q('QD05', '誰が新聞を買う？', 'PERSON', 'ONE', ['兄'], ['S09'])
q('QD05', '誰が朝に薬を渡した？', 'PERSON', 'ONE', ['看護師'], ['S03'])
q('QD05', '誰が店で服を買った？', 'PERSON', 'ONE', ['姉'], ['S08'])
q('QD05', '母はどこで料理を作った？', 'PLACE', 'ONE', ['台所'], ['S06'])
q('QD05', '姉はどこで服を買った？', 'PLACE', 'ONE', ['店'], ['S08'])
q('QD05', '兄はどこで新聞を買う？', 'PLACE', 'NONE')
q('QD05', 'なぜ兄は新聞を買う？', 'CAUSE', 'NONE')
q('QD05', '母はどう料理を作った？', 'MANNER', 'NONE')
q('QD05', 'どんな服を姉は店で買った？', 'PROPERTY', 'NONE')
# ---- QD06 動物・会社
q('QD06', '犬はどこから走った？', 'PLACE', 'SPLIT', ['公園', '森'], ['S01', 'S02'])
q('QD06', '社長はどこから手紙を送った？', 'PLACE', 'ONE', ['会社'], ['S03'])
q('QD06', '医者はどこから薬を送った？', 'PLACE', 'ONE', ['病院'], ['S04'])
q('QD06', '店員はどこから荷物を送った？', 'PLACE', 'ONE', ['駅'], ['S05'])
q('QD06', '医者はどこから手紙を送った？', 'PLACE', 'NONE')
q('QD06', '鳥はどこから飛んだ？', 'PLACE', 'NONE', note='S08 の空は通り道で起点ではない')
q('QD06', '誰が会社から手紙を送った？', 'PERSON', 'ONE', ['社長'], ['S03'])
q('QD06', '誰が駅から荷物を送った？', 'PERSON', 'ONE', ['店員'], ['S05'])
q('QD06', '誰が客に袋を渡さなかった？', 'PERSON', 'ONE', ['店員'], ['S07'])
q('QD06', '誰が公園から走った？', 'PERSON', 'NONE', placement=PL, note='走ったのは犬で、誰（人）ではない。配置で犬が ANIMAL')
q('QD06', '店員は客に何を渡さなかった？', 'THING', 'ONE', ['袋'], ['S07'])
q('QD06', '社長は会社から何を送った？', 'THING', 'ONE', ['手紙'], ['S03'])
q('QD06', '医者は病院から何を送った？', 'THING', 'ONE', ['薬'], ['S04'])
q('QD06', 'どの人が会社から手紙を送った？', 'RESTRICTOR', 'ONE', ['社長'], ['S03'], placement=PL)
q('QD06', 'どの人が公園から走った？', 'RESTRICTOR', 'NONE', placement=PL, note='走ったのは犬（ANIMAL）')
q('QD06', 'どの場所から犬は走った？', 'RESTRICTOR', 'SPLIT', ['公園', '森'], ['S01', 'S02'], placement=PL, note='N=場所（PLACE）')
q('QD06', '犬はいつ公園から走った？', 'TIME', 'NONE')
q('QD06', 'なぜ犬は公園から走った？', 'CAUSE', 'NONE')
q('QD06', '犬はどうやって森から走った？', 'MANNER', 'NONE')
q('QD06', 'どんな荷物を店員は駅から送った？', 'PROPERTY', 'NONE')
q('QD06', '犬は公園へ走ったか？', 'POLAR', 'YESNO')
q('QD06', 'どんな手紙を社長は会社から送った？', 'PROPERTY', 'NONE')
# ---- QD07 家族
q('QD07', '誰が弟に鉛筆を貸した？', 'PERSON', 'ONE', ['兄'], ['S01'])
q('QD07', '誰が兄に鉛筆を貸した？', 'PERSON', 'ONE', ['弟'], ['S07'])
q('QD07', '誰が看護師に薬を渡した？', 'PERSON', 'ONE', ['医者'], ['S03'])
q('QD07', '誰が薬を渡した？', 'PERSON', 'ONE', ['医者'], [], ['S03', 'S04'], note='受取人の腕が多い文だけ')
q('QD07', '医者は誰に薬を渡した？', 'PERSON', 'SPLIT', ['看護師', '患者'], ['S03', 'S04'], note='受取人の穴は読めない位置')
q('QD07', '弟は図書館で何を読んだ？', 'THING', 'ONE', ['本'], ['S05', 'S06'])
q('QD07', '弟は何を読んだ？', 'THING', 'ONE', ['本'], [], ['S05', 'S06'], note='場所の腕が多い文だけ')
q('QD07', '弟は兄に何を貸した？', 'THING', 'ONE', ['鉛筆'], ['S07'])
q('QD07', '妹は姉に何を送った？', 'THING', 'ONE', ['手紙'], ['S02'])
q('QD07', '姉は妹に何を送った？', 'THING', 'NONE')
q('QD07', '医者は看護師に何を渡した？', 'THING', 'ONE', ['薬'], ['S03'])
q('QD07', '弟はどうやって図書館へ行った？', 'MANNER', 'ONE', ['歩いて'], [], [], ['S09'])
q('QD07', 'なぜ兄は弟に鉛筆を貸した？', 'CAUSE', 'NONE')
q('QD07', '弟はどこで本を読んだ？', 'PLACE', 'ONE', ['図書館'], ['S05', 'S06'])
q('QD07', '妹はいつ姉に手紙を送った？', 'TIME', 'NONE')
q('QD07', 'どの人が看護師に薬を渡した？', 'RESTRICTOR', 'ONE', ['医者'], ['S03'], placement=PL)
q('QD07', 'どの人が患者に薬を渡した？', 'RESTRICTOR', 'ONE', ['医者'], ['S04'], placement=PL)
q('QD07', 'どんな鉛筆を兄は弟に貸した？', 'PROPERTY', 'NONE')
q('QD07', '兄か弟が鉛筆を貸した？', 'ILLFORMED', 'ILLFORMED', note='AかB')
q('QD07', '兄は弟に鉛筆を貸したか？', 'POLAR', 'YESNO')
# ---- QD08 英語（市場）
q('QD08', 'Who gave the map to the student?', 'PERSON', 'SPLIT', ['teacher', 'principal'], ['S04', 'S05'])
q('QD08', 'Who sold the map to the chef?', 'PERSON', 'ONE', ['X'], ['S07'], note='印と同じ字 X が正しい答え')
q('QD08', 'Who did the teacher give the map to?', 'PERSON', 'ONE', ['student'], ['S04'], note='取り残しの to（受け手の位置は読めない）')
q('QD08', 'Who bought a horse?', 'PERSON', 'ONE', ['farmer'], ['S01'])
q('QD08', 'Who reads the newspaper?', 'PERSON', 'ONE', ['clerk'], ['S02'])
q('QD08', 'What did the farmer buy?', 'THING', 'ONE', ['horse'], ['S01'])
q('QD08', 'What did the sailor write?', 'THING', 'ONE', ['letter'], ['S03'])
q('QD08', 'What does the clerk read?', 'THING', 'ONE', ['newspaper'], ['S02'])
q('QD08', 'What did the clerk read?', 'THING', 'NONE', note='S02 は非過去')
q('QD08', 'What did the doctor not give to the patient?', 'THING', 'ONE', ['medicine'], ['S06'], note='否定の疑問（書き換えの形に無い）')
q('QD08', 'Where did the farmer buy the horse?', 'PLACE', 'NONE')
q('QD08', 'When did the sailor write a letter?', 'TIME', 'NONE')
q('QD08', 'Why did the farmer buy a horse?', 'CAUSE', 'NONE')
q('QD08', 'How did the sailor write the letter?', 'MANNER', 'NONE')
q('QD08', 'Which person gave the map to the student?', 'RESTRICTOR', 'SPLIT', ['teacher', 'principal'], ['S04', 'S05'], placement=PL)
q('QD08', 'Which animal did the farmer buy?', 'RESTRICTOR', 'ONE', ['horse'], ['S01'], placement=PL)
q('QD08', 'Did the farmer buy a horse?', 'POLAR', 'YESNO')
q('QD08', 'Does the clerk read the newspaper?', 'POLAR', 'YESNO')
q('QD08', 'Who gave what to the student?', 'ILLFORMED', 'ILLFORMED', note='穴が 2 つ')
# ---- QD09 英語（建設）
q('QD09', 'Who built the bridge?', 'PERSON', 'ONE', ['mayor'], ['S03'])
q('QD09', 'Who sold the ship?', 'PERSON', 'NONE', note='S06 は売らなかった')
q('QD09', 'Who gave the map to the student?', 'PERSON', 'NONE', note='S01 は sold。S08 は疑問文')
q('QD09', 'Who sent a letter to the teacher?', 'PERSON', 'ONE', ['student'], ['S07'])
q('QD09', 'Who gave the book to a child?', 'PERSON', 'ONE', ['nurse'], ['S02'])
q('QD09', 'Who did not sell the ship?', 'PERSON', 'ONE', ['captain'], ['S06'], note='否定の疑問（書き換えの形に無い）')
q('QD09', 'What did the pilot fly?', 'THING', 'ONE', ['plane'], ['S04'])
q('QD09', 'What did the painter paint?', 'THING', 'ONE', ['wall'], ['S05'])
q('QD09', 'What did the student send to the teacher?', 'THING', 'ONE', ['letter'], ['S07'])
q('QD09', 'What did the chef sell to the student?', 'THING', 'ONE', ['map'], ['S01'])
q('QD09', 'What did the captain sell?', 'THING', 'NONE', note='S06 は売らなかった')
q('QD09', 'Where did the mayor build the bridge?', 'PLACE', 'NONE')
q('QD09', 'When did the pilot fly the plane?', 'TIME', 'NONE')
q('QD09', 'Why did the captain not sell the ship?', 'CAUSE', 'NONE')
q('QD09', 'How did the painter paint the wall?', 'MANNER', 'NONE')
q('QD09', 'Did the mayor build the bridge?', 'POLAR', 'YESNO')
q('QD09', 'Which person built the bridge?', 'RESTRICTOR', 'ONE', ['mayor'], ['S03'], placement=PL)
# ---- QD10 英語（手紙）
q('QD10', 'Who sent a letter to the teacher?', 'PERSON', 'SPLIT', ['student', 'principal'], ['S03', 'S04'])
q('QD10', 'What did the teacher give the student?', 'THING', 'ONE', ['map'], ['S01'], note='二重目的語。穴の位置が決まらない')
q('QD10', 'What does the clerk read?', 'THING', 'ONE', ['newspaper'], ['S05'])
q('QD10', 'What did the sailor write?', 'THING', 'ONE', ['letter'], ['S06'])
q('QD10', 'Why did the farmer buy a horse?', 'CAUSE', 'ONE', ['the market was open'], [], [], ['S07'], note='S07 が理由を述べる（読解器は読まない）')
q('QD10', 'Why did the sailor write a letter?', 'CAUSE', 'NONE')
q('QD10', 'How did the clerk read the newspaper?', 'MANNER', 'NONE')
q('QD10', 'Who plants the roses?', 'PERSON', 'ONE', ['gardener'], [], [], ['S02'], note='文が読めない')
q('QD10', 'Where does the clerk read the newspaper?', 'PLACE', 'NONE')
q('QD10', 'Which person sent a letter to the teacher?', 'RESTRICTOR', 'SPLIT', ['student', 'principal'], ['S03', 'S04'], placement=PL)
q('QD10', 'When did the student send a letter to the teacher?', 'TIME', 'NONE')
q('QD01', 'どんな本を先生は読む？', 'PROPERTY', 'NONE')
# ---- direction が空でない問
q('QD01', '誰が本を読む？', 'PERSON', 'ONE', ['先生'], ['S07'], direction='FACE_SWAP:agent', note='疑問文の錨に direction を付けた')
q('QD02', '誰が客に切符を渡した？', 'PERSON', 'ONE', ['駅員'], ['S01'], direction='EDGE:cause', note='疑問文の錨に direction を付けた')
# ---- 腕が多い文が別の充填物を隠す問（D9 の限界を測る）
q('QD01', '誰が地図を渡さなかった？', 'PERSON', 'SPLIT', ['校長', '先生'], ['S09'], ['S04'], note='S09（校長）は腕が同じ、S04（先生）は場所の腕が多い')

with open(os.path.join(HERE, 'questions.jsonl'), 'w', encoding='utf-8') as f:
    for r in rows: f.write(json.dumps(r, ensure_ascii=False) + '\n')

def P(*types, state='DECIDED'):
    return {'state': state, 'origin': 'direct', 'types': sorted(types)}
person = ['人', '先生', '校長', '生徒', '駅員', '客', '運転手', '社長', '弟', '兄', '医者', '看護師', '患者', '漁師', '店員', '歌手',
          'person', 'teacher', 'principal', 'mayor', 'student', 'farmer']
artifact = ['物', 'ＰＣ', 'PC', 'カメラ', '車', '地図', '本', '切符', '鉛筆']
animal = ['犬', '馬', 'animal', 'horse']
place = ['場所', '公園', '森', '駅', '港']
lemmas = {}
for w in person: lemmas[w] = P('PERSON')
for w in artifact: lemmas[w] = P('ARTIFACT')
for w in animal: lemmas[w] = P('ANIMAL')
for w in place: lemmas[w] = P('PLACE')
with open(os.path.join(HERE, PL), 'w', encoding='utf-8') as f:
    json.dump({'lemmas': lemmas, 'neighbors': {}}, f, ensure_ascii=False, indent=1, sort_keys=True)
    f.write('\n')
from collections import Counter
print(len(rows), sorted(Counter(r['hole'] for r in rows).items()), 'placement', sum(1 for r in rows if r['placement']), 'direction', sum(1 for r in rows if r['direction']))
print(sorted(Counter(r['truth']['kind'] for r in rows).items()), sorted(Counter(r['lang'] for r in rows).items()))
