"""W3-b4: the sentences of tests/reading_soundness/ja_r10_w3b4.jsonl, written BEFORE the new table was run over any of them (docs/READING_SOUNDNESS.md 10D, K164).
Each call is one row: R = must be read by the new table, A = must be refused (with the reason it should be refused for), X = a type that stays unread. The correct reading
(`roles`) is the one the reading conventions (docs/READING_CONVENTIONS.md section 2) give; the intended reason is a prefix of what `typed_explain_ja(...)['w3b2']` should say.
The groups the ticket requires in the refused rows: (a) one particle that two roles of the same predicate type fit (a split filler or a particle with two readings), (b) a split filler
one candidate of which is outside the row, (c) a particle that is not in the frame of the type, (d) the types of misreading of W1-a4 (an adverb inside a negation, a と, an omitted object),
(e) other gates: a filler placed only by role distributions, an estimated or unplaced filler, a derived predicate, an ending, a voice.
"""
from mk_data_core import add

P = {'ACT': 'P_ACT', 'CHANGE': 'P_CHANGE', 'CREATE': 'P_CREATE', 'CONSUME': 'P_CONSUME', 'EMOTION': 'P_EMOTION', 'GIVE': 'P_GIVE', 'PERCEIVE': 'P_PERCEIVE', 'EXIST': 'P_EXIST',
     'POSSESS': 'P_POSSESS', 'STATE': 'P_STATE', 'COGNITION': 'P_COGNITION'}


def R(typ, text, pred, roles, fill, cons, note=''):
    add(typ, 'R', text, pred, roles, fill, None, cons, note or 'U3 / U: the reader leaves the phrase ambiguous (or names the へ phrase recipient); the type of the fillers decides the roles.', P[typ])


def A(typ, text, pred, reason, fill, cons, roles=None, note=''):
    add(typ, 'A', text, pred, roles, fill, reason, cons, note, P[typ], readable=roles is not None)


def X(typ, text, pred, reason, fill, cons, note=''):
    add(typ, 'X', text, pred, None, fill, reason, cons, note or 'a type that is not read: the plan stops at the type of the predicate', P[typ], readable=False)


def act():
    t = 'ACT'
    # ---- read -------------------------------------------------------------------------------------------------------------------------------------------------------
    R(t, '兄が校庭で遊んだ。', '遊ぶ', {'agent': '兄', 'place': '校庭'}, ['兄', '校庭'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '弟が森林で遊んだ。', '遊ぶ', {'agent': '弟', 'place': '森林'}, ['弟', '森林'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '犬が道路で遊んだ。', '遊ぶ', {'agent': '犬', 'place': '道路'}, ['犬', '道路'], 'agent:が:ANIMAL + place:で:PLACE')
    R(t, '花子が校庭で遊んだ。', '遊ぶ', {'agent': '花子', 'place': '校庭'}, ['花子', '校庭'], 'agent:が:MULTIPLE(全候補が合う: ANIMAL+PERSON) + place:で:PLACE')
    R(t, '姉が歩道で働いた。', '働く', {'agent': '姉', 'place': '歩道'}, ['姉', '歩道'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '先生が校庭で働かなかった。', '働く', {'agent': '先生', 'place': '校庭'}, ['先生', '校庭'], 'agent:が:PERSON + place:で:PLACE(否定 なかった)')
    R(t, '兵士が国道で戦った。', '戦う', {'agent': '兵士', 'place': '国道'}, ['兵士', '国道'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '軍が山林で戦う。', '戦う', {'agent': '軍', 'place': '山林'}, ['軍', '山林'], 'agent:が:GROUP_ORG + place:で:PLACE(非過去)')
    R(t, '選手が土俵で戦った。', '戦う', {'agent': '選手', 'place': '土俵'}, ['選手', '土俵'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '母が校庭で生徒を守った。', '守る', {'agent': '母', 'place': '校庭', 'patient': '生徒'}, ['母', '校庭', '生徒'], 'agent:が + place:で:PLACE + patient:を:PERSON')
    R(t, '警官が交差点で市民を守る。', '守る', {'agent': '警官', 'place': '交差点', 'patient': '市民'}, ['警官', '交差点', '市民'], 'agent:が + place:で:PLACE + patient:を:PERSON(非過去)')
    R(t, '兄が道路で荷車を押した。', '押す', {'agent': '兄', 'place': '道路', 'patient': '荷車'}, ['兄', '道路', '荷車'], 'agent:が + place:で:PLACE + patient:を:ARTIFACT')
    R(t, '父が国道で荷車を引いた。', '引く', {'agent': '父', 'place': '国道', 'patient': '荷車'}, ['父', '国道', '荷車'], 'agent:が + place:で:PLACE + patient:を:ARTIFACT')
    R(t, '農家が農道で荷車を引かなかった。', '引く', {'agent': '農家', 'place': '農道', 'patient': '荷車'}, ['農家', '農道', '荷車'], 'agent:が + place:で:PLACE + patient:を:ARTIFACT(否定)')
    R(t, '母が川で皿を洗った。', '洗う', {'agent': '母', 'place': '川', 'patient': '皿'}, ['母', '川', '皿'], 'agent:が + place:で:PLACE + patient:を:ARTIFACT')
    R(t, '祖母が校舎で箱を拭いた。', '拭く', {'agent': '祖母', 'place': '校舎', 'patient': '箱'}, ['祖母', '校舎', '箱'], 'agent:が + place:で:PLACE + patient:を:ARTIFACT')
    R(t, '弟が山頂で木を切った。', '切る', {'agent': '弟', 'place': '山頂', 'patient': '木'}, ['弟', '山頂', '木'], 'agent:が + place:で:PLACE + patient:を:PLANT')
    R(t, '兄が校庭で草を取り除いた。', '取り除く', {'agent': '兄', 'place': '校庭', 'patient': '草'}, ['兄', '校庭', '草'], 'agent:が + place:で:PLACE + patient:を:PLANT')
    R(t, '母が川で米を洗った。', '洗う', {'agent': '母', 'place': '川', 'patient': '米'}, ['母', '川', '米'], 'patient:を:MULTIPLE(全候補が合う: ARTIFACT+SUBSTANCE_FOOD)')
    R(t, '母が校庭で扉を拭いた。', '拭く', {'agent': '母', 'place': '校庭', 'patient': '扉'}, ['母', '校庭', '扉'], 'patient:を:MULTIPLE(全候補が合う: ARTIFACT+PLANT)')
    R(t, '兄が荷車を畑へ押した。', '押す', {'agent': '兄', 'patient': '荷車', 'goal': '畑'}, ['兄', '荷車', '畑'], 'agent:が + patient:を:ARTIFACT + goal:へ:PLACE')
    R(t, '父が荷車を国道へ引いた。', '引く', {'agent': '父', 'patient': '荷車', 'goal': '国道'}, ['父', '荷車', '国道'], 'agent:が + patient:を:ARTIFACT + goal:へ:PLACE')
    R(t, '弟が荷車を校舎へ引かなかった。', '引く', {'agent': '弟', 'patient': '荷車', 'goal': '校舎'}, ['弟', '荷車', '校舎'], 'agent:が + patient:を + goal:へ:PLACE(否定)')
    R(t, '農家が荷車を農道へ引く。', '引く', {'agent': '農家', 'patient': '荷車', 'goal': '農道'}, ['農家', '荷車', '農道'], 'agent:が + patient:を + goal:へ:PLACE(非過去)')
    R(t, '父が国道で畑から荷車を引いた。', '引く', {'agent': '父', 'place': '国道', 'source': '畑', 'patient': '荷車'}, ['父', '国道', '畑', '荷車'], 'place:で:PLACE + source:から:PLACE + patient:を')
    R(t, '兄が町の校庭で遊んだ。', '遊ぶ', {'agent': '兄', 'place': '町の校庭'}, ['兄', '校庭'], 'place:で:の(主辞 PLACE)')
    # ---- abstain ----------------------------------------------------------------------------------------------------------------------------------------------------
    A(t, '兄が校庭に遊んだ。', '遊ぶ', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_ACT:に', ['兄', '校庭'], '(c) に: する の result・goal・time と型が重なるので表に行が無い')
    A(t, '兄が荷車を校庭に押した。', '押す', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_ACT:に', ['兄', '荷車', '校庭'], '(c) に+PLACE: goal か place か')
    A(t, '兄が学校へ働いた。', '働く', 'PLACEMENT_TYPE_MISMATCH:P_ACT:へ:GROUP_ORG', ['兄', '学校'], 'goal:へ:GROUP_ORG(行き先か相手か。表は PLACE だけ)')
    A(t, '父が荷車を会社へ引いた。', '引く', 'PLACEMENT_TYPE_MISMATCH:P_ACT:へ:GROUP_ORG', ['父', '荷車', '会社'], 'goal:へ:GROUP_ORG(行き先か相手か。規約で決まらないので expect は readable false)')
    A(t, '兄が机で遊んだ。', '遊ぶ', 'PLACEMENT_MULTIPLE:で:机', ['兄', '机'], '(a) place:で:MULTIPLE(ARTIFACT+PLACE: place か instrument か)')
    A(t, '弟が椅子で働いた。', '働く', 'PLACEMENT_MULTIPLE:で:椅子', ['弟', '椅子'], '(a) place:で:MULTIPLE(ARTIFACT+PLACE)')
    A(t, '兄が街角で遊んだ。', '遊ぶ', 'PLACEMENT_MULTIPLE:で:街角', ['兄', '街角'], '(b) place:で:MULTIPLE(PLACE+WORK: 候補の 1 つが PLACE の外)')
    A(t, '母が階段で皿を洗った。', '洗う', 'PLACEMENT_MULTIPLE:で:階段', ['母', '階段', '皿'], '(a) place:で:MULTIPLE(ARTIFACT+PLACE)')
    A(t, '客が校庭で遊んだ。', '遊ぶ', 'PLACEMENT_MULTIPLE:が:客', ['客', '校庭'], '(b) agent:が:MULTIPLE(NATURAL_PHENOMENON+PERSON: 候補の 1 つが外)')
    A(t, '医者が校庭で働いた。', '働く', 'PLACEMENT_MULTIPLE:が:医者', ['医者', '校庭'], '(b) agent:が:MULTIPLE(PERSON+PLACE: 候補の 1 つが外)')
    A(t, '母が校庭で窓を拭いた。', '拭く', 'PLACEMENT_MULTIPLE:を:窓', ['母', '校庭', '窓'], '(b) patient:を:MULTIPLE(ARTIFACT+TIME: TIME が 14 型の外)', roles={'agent': '母', 'place': '校庭', 'patient': '窓'})
    A(t, '弟が国道で水を引いた。', '引く', 'PLACEMENT_MULTIPLE:を:水', ['弟', '国道', '水'], '(b) patient:を:MULTIPLE(SUBSTANCE_FOOD+TIME)', roles={'agent': '弟', 'place': '国道', 'patient': '水'})
    A(t, '母が校庭で荷物を洗った。', '洗う', 'PLACEMENT_UNPLACED:を:荷物', ['母', '校庭', '荷物'], 'patient:を:UNPLACED', roles={'agent': '母', 'place': '校庭', 'patient': '荷物'})
    A(t, '兄が書斎で遊んだ。', '遊ぶ', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:書斎', ['兄', '書斎'], '(e) place:で:PLACE だが腕が role@ だけ(付加の門 5)', roles={'agent': '兄', 'place': '書斎'})
    A(t, '弟が廊下で働いた。', '働く', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:廊下', ['弟', '廊下'], '(e) place:で:PLACE だが腕が role@ だけ(付加の門 5)', roles={'agent': '弟', 'place': '廊下'})
    A(t, '祖母が縁側で皿を拭いた。', '拭く', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:縁側', ['祖母', '縁側', '皿'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '祖母', 'place': '縁側', 'patient': '皿'})
    A(t, '子供が校庭で遊んだ。', '遊ぶ', 'PLACEMENT_DIRECT_VIA_GENERATED:が:子供', ['子供', '校庭'], '(e) agent:が:PERSON だが決め手に生成の腕(門 4)', roles={'agent': '子供', 'place': '校庭'})
    A(t, '委員会が校庭で働いた。', '働く', 'PLACEMENT_ESTIMATED_GENERATED:が:委員会', ['委員会', '校庭'], '(e) agent:が:推定(生成)', roles={'agent': '委員会', 'place': '校庭'})
    A(t, '兵士が校庭で国境を守った。', '守る', 'PLACEMENT_TYPE_MISMATCH:P_ACT:を:PLACE', ['兵士', '校庭', '国境'], '(c) を+PLACE: 経路・対象の を は表の外(patient は PLACE を除く)', roles={'agent': '兵士', 'place': '校庭', 'patient': '国境'})
    A(t, '機械が校庭で働いた。', '働く', 'PLACEMENT_TYPE_MISMATCH:P_ACT:が:ARTIFACT', ['機械', '校庭'], 'agent:が:ARTIFACT(agent の型の外)')
    A(t, '母が機械で皿を洗った。', '洗う', 'PLACEMENT_TYPE_MISMATCH:P_ACT:で:ARTIFACT', ['母', '機械', '皿'], '(c) で の instrument: 規約が型を決めない', roles={'agent': '母', 'instrument': '機械', 'patient': '皿'})
    A(t, '兄があまり校庭で遊ばなかった。', '遊ぶ', 'NT', ['兄', '校庭'], '(d) 否定の中の副詞(あまり + ない)', note='W1-a4 の誤読の型。副詞は規則で足さない')
    A(t, '兄が全然国道で働かなかった。', '働く', 'NT', ['兄', '国道'], '(d) 否定の中の副詞(全然 + ない)')
    A(t, '兄が校庭で犬と遊んだ。', '遊ぶ', 'NT', ['兄', '校庭', '犬'], '(d) と の割れ(companion|quotation)')
    A(t, '兄が荷車を持って、校庭で押した。', '押す', 'NT', ['兄', '荷車', '校庭'], '(d) 目的語の省略(先行詞が別の節にある 2 節の文)')
    A(t, '兄が校庭で皿を集めた。', '集める', 'PLACEMENT_PREDICATE_POSSIBLY_DERIVED', ['兄', '校庭', '皿'], '(e) 派生の門(下一段の述語)', roles={'agent': '兄', 'place': '校庭', 'patient': '皿'})
    A(t, '兄が校庭で遊んでいる。', '遊ぶ', 'PLACEMENT_PREDICATE_TAIL_UNINTERPRETED', ['兄', '校庭'], '(e) 語尾の門(ている)')
    A(t, '兄が校庭で働かされた。', '働く', 'PLACEMENT_VOICE_NOT_ACTIVE', ['兄', '校庭'], '(e) 態(使役受身)')




def change():
    t = 'CHANGE'
    # ---- read -------------------------------------------------------------------------------------------------------------------------------------------------------
    R(t, '兄が校庭で変わった。', '変わる', {'agent': '兄', 'place': '校庭'}, ['兄', '校庭'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '弟が歩道で変わった。', '変わる', {'agent': '弟', 'place': '歩道'}, ['弟', '歩道'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '猫が道路で落ちた。', '落ちる', {'agent': '猫', 'place': '道路'}, ['猫', '道路'], 'agent:が:ANIMAL + place:で:PLACE')
    R(t, '鳥が湖で落ちた。', '落ちる', {'agent': '鳥', 'place': '湖'}, ['鳥', '湖'], 'agent:が:ANIMAL + place:で:PLACE')
    R(t, '兵士が国道で減った。', '減る', {'agent': '兵士', 'place': '国道'}, ['兵士', '国道'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '村人が農道で減った。', '減る', {'agent': '村人', 'place': '農道'}, ['村人', '農道'], 'agent:が:PERSON + place:で:PLACE')
    R(t, '馬が校庭で凍った。', '凍る', {'agent': '馬', 'place': '校庭'}, ['馬', '校庭'], 'agent:が:ANIMAL + place:で:PLACE')
    R(t, '鳥が国道で凍った。', '凍る', {'agent': '鳥', 'place': '国道'}, ['鳥', '国道'], 'agent:が:ANIMAL + place:で:PLACE')
    R(t, '先生が山頂で凍らなかった。', '凍る', {'agent': '先生', 'place': '山頂'}, ['先生', '山頂'], 'agent:が:PERSON + place:で:PLACE(否定)')
    R(t, 'チームが校庭で変わった。', '変わる', {'agent': 'チーム', 'place': '校庭'}, ['チーム', '校庭'], 'agent:が:GROUP_ORG + place:で:PLACE')
    R(t, '軍が山林で広がった。', '広がる', {'agent': '軍', 'place': '山林'}, ['軍', '山林'], 'agent:が:GROUP_ORG + place:で:PLACE')
    R(t, '政府が国道で変わらなかった。', '変わる', {'agent': '政府', 'place': '国道'}, ['政府', '国道'], 'agent:が:GROUP_ORG + place:で:PLACE(否定)')
    R(t, '花子が校庭で落ちた。', '落ちる', {'agent': '花子', 'place': '校庭'}, ['花子', '校庭'], 'agent:が:MULTIPLE(全候補が合う: ANIMAL+PERSON)')
    R(t, '子猫が道路で落ちた。', '落ちる', {'agent': '子猫', 'place': '道路'}, ['子猫', '道路'], 'agent:が:MULTIPLE(全候補が合う: ANIMAL+PERSON)')
    R(t, '警察が交差点で減った。', '減る', {'agent': '警察', 'place': '交差点'}, ['警察', '交差点'], 'agent:が:MULTIPLE(全候補が合う: GROUP_ORG+PERSON)')
    R(t, '猫が屋根へ落ちた。', '落ちる', {'agent': '猫', 'goal': '屋根'}, ['猫', '屋根'], 'agent:が:ANIMAL + goal:へ:PLACE')
    R(t, '鳥が湖へ落ちた。', '落ちる', {'agent': '鳥', 'goal': '湖'}, ['鳥', '湖'], 'agent:が:ANIMAL + goal:へ:PLACE')
    R(t, '兵士が山頂へ広がった。', '広がる', {'agent': '兵士', 'goal': '山頂'}, ['兵士', '山頂'], 'agent:が + goal:へ:PLACE')
    R(t, '村人が校庭へ広がった。', '広がる', {'agent': '村人', 'goal': '校庭'}, ['村人', '校庭'], 'agent:が + goal:へ:PLACE')
    R(t, '犬が池へ落ちた。', '落ちる', {'agent': '犬', 'goal': '池'}, ['犬', '池'], 'agent:が:ANIMAL + goal:へ:PLACE')
    R(t, '兄が畑へ落ちなかった。', '落ちる', {'agent': '兄', 'goal': '畑'}, ['兄', '畑'], 'agent:が + goal:へ:PLACE(否定)')
    R(t, '猫が校庭で屋根から落ちた。', '落ちる', {'agent': '猫', 'place': '校庭', 'source': '屋根'}, ['猫', '校庭', '屋根'], 'place:で:PLACE + source:から:PLACE')
    R(t, '犬が農道で屋根から落ちた。', '落ちる', {'agent': '犬', 'place': '農道', 'source': '屋根'}, ['犬', '農道', '屋根'], 'place:で:PLACE + source:から:PLACE')
    R(t, '兄が山頂で屋根から落ちなかった。', '落ちる', {'agent': '兄', 'place': '山頂', 'source': '屋根'}, ['兄', '山頂', '屋根'], 'place:で + source:から(否定)')
    R(t, '猫が屋根から池へ落ちた。', '落ちる', {'agent': '猫', 'source': '屋根', 'goal': '池'}, ['猫', '屋根', '池'], 'source:から:PLACE + goal:へ:PLACE')
    R(t, '村人が国道から校庭へ広がった。', '広がる', {'agent': '村人', 'source': '国道', 'goal': '校庭'}, ['村人', '国道', '校庭'], 'source:から:PLACE + goal:へ:PLACE')
    R(t, '兄が町の校庭で変わった。', '変わる', {'agent': '兄', 'place': '町の校庭'}, ['兄', '校庭'], 'place:で:の(主辞 PLACE)')
    # ---- abstain ----------------------------------------------------------------------------------------------------------------------------------------------------
    A(t, '兵士が山頂に広がった。', '広がる', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CHANGE:に', ['兵士', '山頂'], '(c) に+PLACE: goal か place か(result とも重なる)')
    A(t, '兄が校庭に落ちた。', '落ちる', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CHANGE:に', ['兄', '校庭'], '(c) に+PLACE: goal か place か')
    A(t, '猫が屋根に落ちた。', '落ちる', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CHANGE:に', ['猫', '屋根'], '(c) に+PLACE: goal か place か')
    A(t, '犬が池に落ちた。', '落ちる', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CHANGE:に', ['犬', '池'], '(c) に+PLACE: goal か place か')
    A(t, '兄が校庭で荷車を落ちた。', '落ちる', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CHANGE:を', ['兄', '校庭', '荷車'], '(c) 自動詞の経路の を の充填物が ARTIFACT(patient の 14 型と重なる。W3-b4 の誤読の型)')
    A(t, '猫が校庭で坂を落ちた。', '落ちる', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CHANGE:を', ['猫', '校庭', '坂'], '(c) 自動詞の経路の を(を+PLACE)')
    A(t, '鳥が国道ではしごを落ちた。', '落ちる', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CHANGE:を', ['鳥', '国道', 'はしご'], '(c) 自動詞の経路の を')
    A(t, '雨が校庭で変わった。', '変わる', 'PLACEMENT_TYPE_MISMATCH:P_CHANGE:が:NATURAL_PHENOMENON', ['雨', '校庭'], 'agent:が:NATURAL_PHENOMENON(entity。agent の型の外)')
    A(t, '雪が国道で減った。', '減る', 'PLACEMENT_TYPE_MISMATCH:P_CHANGE:が:NATURAL_PHENOMENON', ['雪', '国道'], 'agent:が:NATURAL_PHENOMENON')
    A(t, '氷が校庭で広がった。', '広がる', 'PLACEMENT_UNPLACED:が:氷', ['氷', '校庭'], 'agent:が:UNPLACED')
    A(t, '客が校庭で減った。', '減る', 'PLACEMENT_MULTIPLE:が:客', ['客', '校庭'], '(b) agent:が:MULTIPLE(NATURAL_PHENOMENON+PERSON: 候補の 1 つが外)')
    A(t, '医者が国道で変わった。', '変わる', 'PLACEMENT_MULTIPLE:が:医者', ['医者', '国道'], '(b) agent:が:MULTIPLE(PERSON+PLACE)')
    A(t, '猫が階段で落ちた。', '落ちる', 'PLACEMENT_MULTIPLE:で:階段', ['猫', '階段'], '(a) place:で:MULTIPLE(ARTIFACT+PLACE: place か instrument か)')
    A(t, '鳥が街角で減った。', '減る', 'PLACEMENT_MULTIPLE:で:街角', ['鳥', '街角'], '(b) place:で:MULTIPLE(PLACE+WORK)')
    A(t, '猫が階段へ落ちた。', '落ちる', 'PLACEMENT_MULTIPLE:へ:階段', ['猫', '階段'], '(b) goal:へ:MULTIPLE(ARTIFACT+PLACE: 候補の 1 つが PLACE の外)')
    A(t, '犬が裏庭へ落ちた。', '落ちる', 'PLACEMENT_UNPLACED:へ:裏庭', ['犬', '裏庭'], 'goal:へ:UNPLACED', roles={'agent': '犬', 'goal': '裏庭'})
    A(t, 'チームが会社へ広がった。', '広がる', 'PLACEMENT_TYPE_MISMATCH:P_CHANGE:へ:GROUP_ORG', ['チーム', '会社'], 'goal:へ:GROUP_ORG(行き先か相手か)')
    A(t, '村人が学校へ広がった。', '広がる', 'PLACEMENT_TYPE_MISMATCH:P_CHANGE:へ:GROUP_ORG', ['村人', '学校'], 'goal:へ:GROUP_ORG')
    A(t, '猫が屋根で落ちた。', '落ちる', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:屋根', ['猫', '屋根'], '(e) place:で:PLACE だが腕が role@ だけ(付加の門 5)', roles={'agent': '猫', 'place': '屋根'})
    A(t, '兄が書斎で変わった。', '変わる', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:書斎', ['兄', '書斎'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '兄', 'place': '書斎'})
    A(t, '弟が廊下で落ちた。', '落ちる', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:廊下', ['弟', '廊下'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '弟', 'place': '廊下'})
    A(t, '子供が校庭で落ちた。', '落ちる', 'PLACEMENT_DIRECT_VIA_GENERATED:が:子供', ['子供', '校庭'], '(e) agent:が:PERSON だが決め手に生成の腕(門 4)', roles={'agent': '子供', 'place': '校庭'})
    A(t, '委員会が国道で変わった。', '変わる', 'PLACEMENT_ESTIMATED_GENERATED:が:委員会', ['委員会', '国道'], '(e) agent:が:推定(生成)', roles={'agent': '委員会', 'place': '国道'})
    A(t, '兄があまり校庭で変わらなかった。', '変わる', 'NT', ['兄', '校庭'], '(d) 否定の中の副詞(あまり + ない)')
    A(t, '兄が全然国道で終わらなかった。', '終わる', 'NT', ['兄', '国道'], '(d) 否定の中の副詞(全然 + ない)')
    A(t, '兄が校庭で犬と変わらなかった。', '変わる', 'NT', ['兄', '校庭', '犬'], '(d) と の割れ(companion|quotation|比較)')
    A(t, '兄が荷車を引いて、校庭で落ちた。', '落ちる', 'NT', ['兄', '荷車', '校庭'], '(d) 2 節の文(後の節の主語・目的語の省略)')
    A(t, '兄が校庭で消えた。', '消える', 'PLACEMENT_PREDICATE_POSSIBLY_DERIVED', ['兄', '校庭'], '(e) 派生の門(下一段の述語)', roles={'agent': '兄', 'place': '校庭'})
    A(t, '猫が道路で消えた。', '消える', 'PLACEMENT_PREDICATE_POSSIBLY_DERIVED', ['猫', '道路'], '(e) 派生の門(下一段の述語)', roles={'agent': '猫', 'place': '道路'})
    A(t, '兄が校庭で変わっている。', '変わる', 'PLACEMENT_PREDICATE_TAIL_UNINTERPRETED', ['兄', '校庭'], '(e) 語尾の門(ている)')


def create():
    t = 'CREATE'
    # ---- read -------------------------------------------------------------------------------------------------------------------------------------------------------
    R(t, '父が校庭で絵を描いた。', '描く', {'agent': '父', 'place': '校庭', 'patient': '絵'}, ['父', '校庭', '絵'], 'agent:が + place:で:PLACE + patient:を:WORK')
    R(t, '姉が森林で絵を描いた。', '描く', {'agent': '姉', 'place': '森林', 'patient': '絵'}, ['姉', '森林', '絵'], 'agent:が + place:で:PLACE + patient:を:WORK')
    R(t, '母が校庭で歌を作った。', '作る', {'agent': '母', 'place': '校庭', 'patient': '歌'}, ['母', '校庭', '歌'], 'agent:が + place:で:PLACE + patient:を:WORK')
    R(t, '兄が国道で規則を作った。', '作る', {'agent': '兄', 'place': '国道', 'patient': '規則'}, ['兄', '国道', '規則'], 'agent:が + place:で:PLACE + patient:を:ABSTRACT')
    R(t, '先生が校舎で約束を作った。', '作る', {'agent': '先生', 'place': '校舎', 'patient': '約束'}, ['先生', '校舎', '約束'], 'agent:が + place:で:PLACE + patient:を:EVENT_ACT')
    R(t, '兄が校庭で手紙を書いた。', '書く', {'agent': '兄', 'place': '校庭', 'patient': '手紙'}, ['兄', '校庭', '手紙'], 'patient:を:MULTIPLE(全候補が合う: ABSTRACT+IDENTIFIER+INFO_LANGUAGE+WORK)')
    R(t, '弟が校舎で日記を書いた。', '書く', {'agent': '弟', 'place': '校舎', 'patient': '日記'}, ['弟', '校舎', '日記'], 'patient:を:MULTIPLE(全候補が合う: EVENT_ACT+INFO_LANGUAGE+WORK)')
    R(t, '姉が湖で絵本を描いた。', '描く', {'agent': '姉', 'place': '湖', 'patient': '絵本'}, ['姉', '湖', '絵本'], 'patient:を:MULTIPLE(全候補が合う: ARTIFACT+INFO_LANGUAGE+WORK)')
    R(t, '母が校庭で魚を焼いた。', '焼く', {'agent': '母', 'place': '校庭', 'patient': '魚'}, ['母', '校庭', '魚'], 'agent:が + place:で:PLACE + patient:を:ANIMAL')
    R(t, '祖母が校庭で肉を焼かなかった。', '焼く', {'agent': '祖母', 'place': '校庭', 'patient': '肉'}, ['祖母', '校庭', '肉'], 'patient:を:SUBSTANCE_FOOD(否定)')
    R(t, '母が川で野菜を煮た。', '煮る', {'agent': '母', 'place': '川', 'patient': '野菜'}, ['母', '川', '野菜'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '父が山頂で豆を煮た。', '煮る', {'agent': '父', 'place': '山頂', 'patient': '豆'}, ['父', '山頂', '豆'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '祖父が山林で芋を掘った。', '掘る', {'agent': '祖父', 'place': '山林', 'patient': '芋'}, ['祖父', '山林', '芋'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '農家が農道で芋を掘る。', '掘る', {'agent': '農家', 'place': '農道', 'patient': '芋'}, ['農家', '農道', '芋'], 'patient:を:SUBSTANCE_FOOD(非過去)')
    R(t, '祖母が校庭で帽子を編んだ。', '編む', {'agent': '祖母', 'place': '校庭', 'patient': '帽子'}, ['祖母', '校庭', '帽子'], 'patient:を:ARTIFACT')
    R(t, '母が校舎で服を縫った。', '縫う', {'agent': '母', 'place': '校舎', 'patient': '服'}, ['母', '校舎', '服'], 'patient:を:ARTIFACT')
    R(t, '母が校庭で米を炊いた。', '炊く', {'agent': '母', 'place': '校庭', 'patient': '米'}, ['母', '校庭', '米'], 'patient:を:MULTIPLE(全候補が合う: ARTIFACT+SUBSTANCE_FOOD)')
    R(t, '母が国道で卵焼きを作った。', '作る', {'agent': '母', 'place': '国道', 'patient': '卵焼き'}, ['母', '国道', '卵焼き'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '母が校庭で餅を作らなかった。', '作る', {'agent': '母', 'place': '校庭', 'patient': '餅'}, ['母', '校庭', '餅'], 'patient:を:SUBSTANCE_FOOD(否定)')
    R(t, '兄が校庭でスープを作った。', '作る', {'agent': '兄', 'place': '校庭', 'patient': 'スープ'}, ['兄', '校庭', 'スープ'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '先生が校庭で絵を描かなかった。', '描く', {'agent': '先生', 'place': '校庭', 'patient': '絵'}, ['先生', '校庭', '絵'], 'patient:を:WORK(否定)')
    R(t, '弟が遊歩道で歌を書いた。', '書く', {'agent': '弟', 'place': '遊歩道', 'patient': '歌'}, ['弟', '遊歩道', '歌'], 'patient:を:WORK')
    R(t, '祖母が神社で餅を焼いた。', '焼く', {'agent': '祖母', 'place': '神社', 'patient': '餅'}, ['祖母', '神社', '餅'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '父が教会で絵を描いた。', '描く', {'agent': '父', 'place': '教会', 'patient': '絵'}, ['父', '教会', '絵'], 'patient:を:WORK')
    R(t, '花子が校庭で絵を描いた。', '描く', {'agent': '花子', 'place': '校庭', 'patient': '絵'}, ['花子', '校庭', '絵'], 'agent:が:MULTIPLE(全候補が合う: ANIMAL+PERSON)')
    R(t, '警察が交差点で規則を作った。', '作る', {'agent': '警察', 'place': '交差点', 'patient': '規則'}, ['警察', '交差点', '規則'], 'agent:が:MULTIPLE(全候補が合う: GROUP_ORG+PERSON)')
    R(t, '母が町の校庭でスープを煮た。', '煮る', {'agent': '母', 'place': '町の校庭', 'patient': 'スープ'}, ['母', '校庭', 'スープ'], 'place:で:の(主辞 PLACE)')
    R(t, '兄が山頂で音楽を作った。', '作る', {'agent': '兄', 'place': '山頂', 'patient': '音楽'}, ['兄', '山頂', '音楽'], 'patient:を:WORK')
    # ---- abstain ----------------------------------------------------------------------------------------------------------------------------------------------------
    A(t, '母が兄に帽子を編んだ。', '編む', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CREATE:に', ['母', '兄', '帽子'], '(c) に+人: recipient か beneficiary か')
    A(t, '母が弟にスープを作った。', '作る', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CREATE:に', ['母', '弟', 'スープ'], '(c) に+人: recipient か beneficiary か')
    A(t, '祖母が妹に服を縫った。', '縫う', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CREATE:に', ['祖母', '妹', '服'], '(c) に+人: recipient か beneficiary か')
    A(t, '姉が妹に絵を描いた。', '描く', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CREATE:に', ['姉', '妹', '絵'], '(c) に+人: recipient か beneficiary か')
    A(t, '祖父が山頂に芋を掘った。', '掘る', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CREATE:に', ['祖父', '山頂', '芋'], '(c) に+PLACE: goal か place か')
    A(t, '母が兄へ服を縫った。', '縫う', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CREATE:へ', ['母', '兄', '服'], '(c) へ: 表に行が無い(用例が乏しい)')
    A(t, '兄が校庭で川から芋を掘った。', '掘る', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CREATE:から', ['兄', '校庭', '川', '芋'], '(c) から: 表に行が無い(用例が乏しい)')
    A(t, '兄が校庭で橋を築いた。', '築く', 'PLACEMENT_TYPE_MISMATCH:P_CREATE:を:PLACE', ['兄', '校庭', '橋'], 'patient:を:PLACE(作る対象が場所。patient は PLACE を除く)', roles={'agent': '兄', 'place': '校庭', 'patient': '橋'})
    A(t, '兵士が国道で井戸を掘った。', '掘る', 'PLACEMENT_TYPE_MISMATCH:P_CREATE:を:PLACE', ['兵士', '国道', '井戸'], 'patient:を:PLACE', roles={'agent': '兵士', 'place': '国道', 'patient': '井戸'})
    A(t, '機械が校庭で絵を描いた。', '描く', 'PLACEMENT_TYPE_MISMATCH:P_CREATE:が:ARTIFACT', ['機械', '校庭', '絵'], 'agent:が:ARTIFACT')
    A(t, '風が森林で歌を作った。', '作る', 'PLACEMENT_TYPE_MISMATCH:P_CREATE:が:NATURAL_PHENOMENON', ['風', '森林', '歌'], 'agent:が:NATURAL_PHENOMENON')
    A(t, '客が校庭で絵を描いた。', '描く', 'PLACEMENT_MULTIPLE:が:客', ['客', '校庭', '絵'], '(b) agent:が:MULTIPLE(NATURAL_PHENOMENON+PERSON)')
    A(t, '母が校庭で窓を作った。', '作る', 'PLACEMENT_MULTIPLE:を:窓', ['母', '校庭', '窓'], '(b) patient:を:MULTIPLE(ARTIFACT+TIME)', roles={'agent': '母', 'place': '校庭', 'patient': '窓'})
    A(t, '母が校庭で水を煮た。', '煮る', 'PLACEMENT_MULTIPLE:を:水', ['母', '校庭', '水'], '(b) patient:を:MULTIPLE(SUBSTANCE_FOOD+TIME)', roles={'agent': '母', 'place': '校庭', 'patient': '水'})
    A(t, '母が校庭で紙を作った。', '作る', 'PLACEMENT_UNPLACED:を:紙', ['母', '校庭', '紙'], 'patient:を:UNPLACED', roles={'agent': '母', 'place': '校庭', 'patient': '紙'})
    A(t, '加藤が校庭で絵を描いた。', '描く', 'PLACEMENT_UNPLACED:が:加藤', ['加藤', '校庭', '絵'], 'agent:が:UNPLACED(固有名)', roles={'agent': '加藤', 'place': '校庭', 'patient': '絵'})
    A(t, '母が校庭で石鹸を作った。', '作る', 'PLACEMENT_ESTIMATED_GENERATED:を:石鹸', ['母', '校庭', '石鹸'], '(e) patient:を:推定(生成)', roles={'agent': '母', 'place': '校庭', 'patient': '石鹸'})
    A(t, '兄が校庭で報告書を書いた。', '書く', 'PLACEMENT_ESTIMATED_GENERATED:を:報告書', ['兄', '校庭', '報告書'], '(e) patient:を:推定(生成)', roles={'agent': '兄', 'place': '校庭', 'patient': '報告書'})
    A(t, '兄が書斎で手紙を書いた。', '書く', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:書斎', ['兄', '書斎', '手紙'], '(e) place:で:PLACE だが腕が role@ だけ(付加の門 5)', roles={'agent': '兄', 'place': '書斎', 'patient': '手紙'})
    A(t, '母が居間で絵を描いた。', '描く', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:居間', ['母', '居間', '絵'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '母', 'place': '居間', 'patient': '絵'})
    A(t, '父が縁側で歌を作った。', '作る', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:縁側', ['父', '縁側', '歌'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '父', 'place': '縁側', 'patient': '歌'})
    A(t, '兄が机で絵を描いた。', '描く', 'PLACEMENT_MULTIPLE:で:机', ['兄', '机', '絵'], '(a) place:で:MULTIPLE(ARTIFACT+PLACE: place か instrument か)')
    A(t, '母が階段で絵を描いた。', '描く', 'PLACEMENT_MULTIPLE:で:階段', ['母', '階段', '絵'], '(a) place:で:MULTIPLE(ARTIFACT+PLACE)')
    A(t, '母が機械で餅を作った。', '作る', 'PLACEMENT_TYPE_MISMATCH:P_CREATE:で:ARTIFACT', ['母', '機械', '餅'], '(a) で の instrument(ARTIFACT)か place か', roles={'agent': '母', 'instrument': '機械', 'patient': '餅'})
    A(t, '兄があまり校庭で絵を描かなかった。', '描く', 'NT', ['兄', '校庭', '絵'], '(d) 否定の中の副詞(あまり + ない)')
    A(t, '兄が全然校庭で歌を作らなかった。', '作る', 'NT', ['兄', '校庭', '歌'], '(d) 否定の中の副詞(全然 + ない)')
    A(t, '兄が校庭で弟と絵を描いた。', '描く', 'NT', ['兄', '校庭', '弟', '絵'], '(d) と(companion。6 つの助詞の外。読解器が と を割る)', roles={'agent': '兄', 'place': '校庭', 'companion': '弟', 'patient': '絵'})
    A(t, '母が餅を作って、校庭で焼いた。', '焼く', 'NT', ['母', '餅', '校庭'], '(d) 目的語の省略(先行詞が別の節にある 2 節の文)')
    A(t, '母が校庭で魚を揚げた。', '揚げる', 'PLACEMENT_PREDICATE_POSSIBLY_DERIVED', ['母', '校庭', '魚'], '(e) 派生の門(下一段の述語)', roles={'agent': '母', 'place': '校庭', 'patient': '魚'})
    A(t, '祖父が校庭で花を育てた。', '育てる', 'PLACEMENT_PREDICATE_POSSIBLY_DERIVED', ['祖父', '校庭', '花'], '(e) 派生の門(下一段の述語)', roles={'agent': '祖父', 'place': '校庭', 'patient': '花'})
    A(t, '母が校庭で魚を焼いている。', '焼く', 'PLACEMENT_PREDICATE_TAIL_UNINTERPRETED', ['母', '校庭', '魚'], '(e) 語尾の門(ている)')
    A(t, '母が校庭で餅を作らせた。', '作る', 'PLACEMENT_VOICE_NOT_ACTIVE', ['母', '校庭', '餅'], '(e) 態(使役)')


def consume():
    t = 'CONSUME'
    # ---- read -------------------------------------------------------------------------------------------------------------------------------------------------------
    R(t, '兄が校庭で薬を飲んだ。', '飲む', {'agent': '兄', 'place': '校庭', 'patient': '薬'}, ['兄', '校庭', '薬'], 'agent:が + place:で:PLACE + patient:を:SUBSTANCE_FOOD')
    R(t, '弟が森林で酒を飲んだ。', '飲む', {'agent': '弟', 'place': '森林', 'patient': '酒'}, ['弟', '森林', '酒'], 'agent:が + place:で:PLACE + patient:を:SUBSTANCE_FOOD')
    R(t, '祖母が神社で茶を飲んだ。', '飲む', {'agent': '祖母', 'place': '神社', 'patient': '茶'}, ['祖母', '神社', '茶'], 'agent:が + place:で:PLACE + patient:を:SUBSTANCE_FOOD')
    R(t, '母が川で薬を飲まなかった。', '飲む', {'agent': '母', 'place': '川', 'patient': '薬'}, ['母', '川', '薬'], 'patient:を:SUBSTANCE_FOOD(否定)')
    R(t, '兄が校庭で道具を使った。', '使う', {'agent': '兄', 'place': '校庭', 'patient': '道具'}, ['兄', '校庭', '道具'], 'agent:が + place:で:PLACE + patient:を:ARTIFACT')
    R(t, '弟が道路で機械を使った。', '使う', {'agent': '弟', 'place': '道路', 'patient': '機械'}, ['弟', '道路', '機械'], 'patient:を:ARTIFACT')
    R(t, '先生が校舎で道具を用いた。', '用いる', {'agent': '先生', 'place': '校舎', 'patient': '道具'}, ['先生', '校舎', '道具'], 'patient:を:ARTIFACT')
    R(t, '先生が校庭で規則を用いた。', '用いる', {'agent': '先生', 'place': '校庭', 'patient': '規則'}, ['先生', '校庭', '規則'], 'patient:を:ABSTRACT')
    R(t, '兄が校庭で服を着た。', '着る', {'agent': '兄', 'place': '校庭', 'patient': '服'}, ['兄', '校庭', '服'], 'patient:を:ARTIFACT')
    R(t, '弟が森林で帽子を脱いだ。', '脱ぐ', {'agent': '弟', 'place': '森林', 'patient': '帽子'}, ['弟', '森林', '帽子'], 'patient:を:ARTIFACT')
    R(t, '姉が教会で服を脱がなかった。', '脱ぐ', {'agent': '姉', 'place': '教会', 'patient': '服'}, ['姉', '教会', '服'], 'patient:を:ARTIFACT(否定)')
    R(t, '農家が農道で肉を噛んだ。', '噛む', {'agent': '農家', 'place': '農道', 'patient': '肉'}, ['農家', '農道', '肉'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '兄が校庭で豆を噛んだ。', '噛む', {'agent': '兄', 'place': '校庭', 'patient': '豆'}, ['兄', '校庭', '豆'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '母が神社で餅を味わった。', '味わう', {'agent': '母', 'place': '神社', 'patient': '餅'}, ['母', '神社', '餅'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '祖父が山頂で酒を味わう。', '味わう', {'agent': '祖父', 'place': '山頂', 'patient': '酒'}, ['祖父', '山頂', '酒'], 'patient:を:SUBSTANCE_FOOD(非過去)')
    R(t, '父が国道で油を使った。', '使う', {'agent': '父', 'place': '国道', 'patient': '油'}, ['父', '国道', '油'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '兄が校庭で歌を味わった。', '味わう', {'agent': '兄', 'place': '校庭', 'patient': '歌'}, ['兄', '校庭', '歌'], 'patient:を:WORK')
    R(t, '母が川で米を使った。', '使う', {'agent': '母', 'place': '川', 'patient': '米'}, ['母', '川', '米'], 'patient:を:MULTIPLE(全候補が合う: ARTIFACT+SUBSTANCE_FOOD)')
    R(t, '兄が校庭で手紙を用いた。', '用いる', {'agent': '兄', 'place': '校庭', 'patient': '手紙'}, ['兄', '校庭', '手紙'], 'patient:を:MULTIPLE(全候補が合う: ABSTRACT+IDENTIFIER+INFO_LANGUAGE+WORK)')
    R(t, '兄が夜に校庭で薬を飲んだ。', '飲む', {'agent': '兄', 'time': '夜', 'place': '校庭', 'patient': '薬'}, ['兄', '夜', '校庭', '薬'], 'time:に:TIME + place:で:PLACE + patient:を')
    R(t, '弟が放課後に校庭で道具を使った。', '使う', {'agent': '弟', 'time': '放課後', 'place': '校庭', 'patient': '道具'}, ['弟', '放課後', '校庭', '道具'], 'time:に:TIME + place:で:PLACE + patient:を')
    R(t, '祖母が休日に神社で茶を飲んだ。', '飲む', {'agent': '祖母', 'time': '休日', 'place': '神社', 'patient': '茶'}, ['祖母', '休日', '神社', '茶'], 'time:に:TIME + place:で:PLACE + patient:を')
    R(t, '兄が冬に山頂で酒を飲んだ。', '飲む', {'agent': '兄', 'time': '冬', 'place': '山頂', 'patient': '酒'}, ['兄', '冬', '山頂', '酒'], 'time:に:TIME + place:で:PLACE + patient:を')
    R(t, '母が祝日に川で服を着た。', '着る', {'agent': '母', 'time': '祝日', 'place': '川', 'patient': '服'}, ['母', '祝日', '川', '服'], 'time:に:TIME + place:で:PLACE + patient:を')
    R(t, '先生が昼に校庭で薬を飲まなかった。', '飲む', {'agent': '先生', 'time': '昼', 'place': '校庭', 'patient': '薬'}, ['先生', '昼', '校庭', '薬'], 'time:に:TIME + place:で:PLACE(否定)')
    R(t, '父が年末に湖で酒を味わった。', '味わう', {'agent': '父', 'time': '年末', 'place': '湖', 'patient': '酒'}, ['父', '年末', '湖', '酒'], 'time:に:TIME + place:で:PLACE + patient:を')
    R(t, '弟が国道で酒を飲み込んだ。', '飲み込む', {'agent': '弟', 'place': '国道', 'patient': '酒'}, ['弟', '国道', '酒'], 'agent:が + place:で + patient:を(複合動詞 飲み込む)')
    R(t, '兄が校庭で川から茶を飲んだ。', '飲む', {'agent': '兄', 'place': '校庭', 'source': '川', 'patient': '茶'}, ['兄', '校庭', '川', '茶'], 'place:で:PLACE + source:から:PLACE + patient:を')
    R(t, '母が町の校庭で薬を飲んだ。', '飲む', {'agent': '母', 'place': '町の校庭', 'patient': '薬'}, ['母', '校庭', '薬'], 'place:で:の(主辞 PLACE)')
    # ---- abstain ----------------------------------------------------------------------------------------------------------------------------------------------------
    A(t, '兄が夕食に薬を飲んだ。', '飲む', 'PLACEMENT_TYPE_MISMATCH:P_CONSUME:に:SUBSTANCE_FOOD', ['兄', '夕食', '薬'], '(a) に: 夕食 は SUBSTANCE_FOOD(時にも目的にも読める。表の に は TIME だけ)')
    A(t, '弟が夕食に道具を使った。', '使う', 'PLACEMENT_TYPE_MISMATCH:P_CONSUME:に:SUBSTANCE_FOOD', ['弟', '夕食', '道具'], '(a) に: 夕食(時か目的か)')
    A(t, '母が弁当に服を着た。', '着る', 'PLACEMENT_TYPE_MISMATCH:P_CONSUME:に:SUBSTANCE_FOOD', ['母', '弁当', '服'], '(c) に+SUBSTANCE_FOOD(目的)')
    A(t, '弟が畑へ酒を飲んだ。', '飲む', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_CONSUME:へ', ['弟', '畑', '酒'], '(c) へ: 表に行が無い(CONSUME の goal は読まない)')
    A(t, '兄が机で薬を飲んだ。', '飲む', 'PLACEMENT_MULTIPLE:で:机', ['兄', '机', '薬'], '(a) place:で:MULTIPLE(ARTIFACT+PLACE: place か instrument か)')
    A(t, '母が階段で服を着た。', '着る', 'PLACEMENT_MULTIPLE:で:階段', ['母', '階段', '服'], '(a) place:で:MULTIPLE(ARTIFACT+PLACE)')
    A(t, '弟が街角で酒を飲んだ。', '飲む', 'PLACEMENT_MULTIPLE:で:街角', ['弟', '街角', '酒'], '(b) place:で:MULTIPLE(PLACE+WORK)')
    A(t, '兄が書斎で薬を飲んだ。', '飲む', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:書斎', ['兄', '書斎', '薬'], '(e) place:で:PLACE だが腕が role@ だけ(付加の門 5)', roles={'agent': '兄', 'place': '書斎', 'patient': '薬'})
    A(t, '母が居間で服を着た。', '着る', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:居間', ['母', '居間', '服'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '母', 'place': '居間', 'patient': '服'})
    A(t, '祖父が縁側で茶を飲んだ。', '飲む', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:縁側', ['祖父', '縁側', '茶'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '祖父', 'place': '縁側', 'patient': '茶'})
    A(t, '弟が廊下で道具を使った。', '使う', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:廊下', ['弟', '廊下', '道具'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '弟', 'place': '廊下', 'patient': '道具'})
    A(t, '兄が馬車で薬を飲んだ。', '飲む', 'PLACEMENT_TYPE_MISMATCH:P_CONSUME:で:ARTIFACT', ['兄', '馬車', '薬'], '(a) で の instrument(ARTIFACT)か place か')
    A(t, '兄が国道で湖を味わった。', '味わう', 'PLACEMENT_TYPE_MISMATCH:P_CONSUME:を:PLACE', ['兄', '国道', '湖'], '(c) を+PLACE(対象。patient は PLACE を除く)', roles={'agent': '兄', 'place': '国道', 'patient': '湖'})
    A(t, '兄が校庭で川を使った。', '使う', 'PLACEMENT_TYPE_MISMATCH:P_CONSUME:を:PLACE', ['兄', '校庭', '川'], '(c) を+PLACE', roles={'agent': '兄', 'place': '校庭', 'patient': '川'})
    A(t, '機械が校庭で薬を飲んだ。', '飲む', 'PLACEMENT_TYPE_MISMATCH:P_CONSUME:が:ARTIFACT', ['機械', '校庭', '薬'], 'agent:が:ARTIFACT')
    A(t, '風が森林で酒を飲んだ。', '飲む', 'PLACEMENT_TYPE_MISMATCH:P_CONSUME:が:NATURAL_PHENOMENON', ['風', '森林', '酒'], 'agent:が:NATURAL_PHENOMENON')
    A(t, '客が校庭で薬を飲んだ。', '飲む', 'PLACEMENT_MULTIPLE:が:客', ['客', '校庭', '薬'], '(b) agent:が:MULTIPLE(NATURAL_PHENOMENON+PERSON)')
    A(t, '兄が校庭で水を飲んだ。', '飲む', 'PLACEMENT_MULTIPLE:を:水', ['兄', '校庭', '水'], '(b) patient:を:MULTIPLE(SUBSTANCE_FOOD+TIME)', roles={'agent': '兄', 'place': '校庭', 'patient': '水'})
    A(t, '弟が国道でご飯を味わった。', '味わう', 'PLACEMENT_MULTIPLE:を:ご飯', ['弟', '国道', 'ご飯'], '(b) patient:を:MULTIPLE(SUBSTANCE_FOOD+TIME)', roles={'agent': '弟', 'place': '国道', 'patient': 'ご飯'})
    A(t, '母が校庭で窓を使った。', '使う', 'PLACEMENT_MULTIPLE:を:窓', ['母', '校庭', '窓'], '(b) patient:を:MULTIPLE(ARTIFACT+TIME)', roles={'agent': '母', 'place': '校庭', 'patient': '窓'})
    A(t, '兄が校庭で靴を履いた。', '履く', 'PLACEMENT_UNPLACED:を:靴', ['兄', '校庭', '靴'], 'patient:を:UNPLACED', roles={'agent': '兄', 'place': '校庭', 'patient': '靴'})
    A(t, '弟が国道で荷物を使った。', '使う', 'PLACEMENT_UNPLACED:を:荷物', ['弟', '国道', '荷物'], 'patient:を:UNPLACED', roles={'agent': '弟', 'place': '国道', 'patient': '荷物'})
    A(t, '兄が校庭で傘を使った。', '使う', 'PLACEMENT_DIRECT_VIA_GENERATED:を:傘', ['兄', '校庭', '傘'], '(e) patient:を:ARTIFACT だが決め手に生成の腕(門 4)', roles={'agent': '兄', 'place': '校庭', 'patient': '傘'})
    A(t, '兄が校庭でズボンを履いた。', '履く', 'PLACEMENT_ESTIMATED_GENERATED:を:ズボン', ['兄', '校庭', 'ズボン'], '(e) patient:を:推定(生成)', roles={'agent': '兄', 'place': '校庭', 'patient': 'ズボン'})
    A(t, '子供が校庭で薬を飲んだ。', '飲む', 'PLACEMENT_DIRECT_VIA_GENERATED:が:子供', ['子供', '校庭', '薬'], '(e) agent:が:PERSON だが決め手に生成の腕', roles={'agent': '子供', 'place': '校庭', 'patient': '薬'})
    A(t, '兄が校庭で肉を食べた。', '食べる', 'PLACEMENT_PREDICATE_POSSIBLY_DERIVED', ['兄', '校庭', '肉'], '(e) 派生の門(下一段の述語)', roles={'agent': '兄', 'place': '校庭', 'patient': '肉'})
    A(t, '兄があまり校庭で薬を飲まなかった。', '飲む', 'NT', ['兄', '校庭', '薬'], '(d) 否定の中の副詞(あまり + ない)')
    A(t, '兄が全然校庭で服を着なかった。', '着る', 'NT', ['兄', '校庭', '服'], '(d) 否定の中の副詞(全然 + ない)')
    A(t, '兄が校庭で弟と薬を飲んだ。', '飲む', 'NT', ['兄', '校庭', '弟', '薬'], '(d) と(companion。6 つの助詞の外)', roles={'agent': '兄', 'place': '校庭', 'companion': '弟', 'patient': '薬'})
    A(t, '母が薬を買って、校庭で飲んだ。', '飲む', 'NT', ['母', '薬', '校庭'], '(d) 目的語の省略(先行詞が別の節にある 2 節の文)')
    A(t, '兄が校庭で薬を飲んでいる。', '飲む', 'PLACEMENT_PREDICATE_TAIL_UNINTERPRETED', ['兄', '校庭', '薬'], '(e) 語尾の門(ている)')
    A(t, '母が校庭で薬を飲ませた。', '飲む', 'PLACEMENT_VOICE_NOT_ACTIVE', ['母', '校庭', '薬'], '(e) 態(使役)')


def emotion():
    t = 'EMOTION'
    # ---- read -------------------------------------------------------------------------------------------------------------------------------------------------------
    R(t, '兄が校庭で泣いた。', '泣く', {'agent': '兄', 'place': '校庭'}, ['兄', '校庭'], 'agent:が + place:で:PLACE')
    R(t, '弟が森林で泣いた。', '泣く', {'agent': '弟', 'place': '森林'}, ['弟', '森林'], 'agent:が + place:で:PLACE')
    R(t, '姉が歩道で泣いた。', '泣く', {'agent': '姉', 'place': '歩道'}, ['姉', '歩道'], 'agent:が + place:で:PLACE')
    R(t, '先生が校庭で泣かなかった。', '泣く', {'agent': '先生', 'place': '校庭'}, ['先生', '校庭'], 'agent:が + place:で:PLACE(否定)')
    R(t, '母が山頂で笑った。', '笑う', {'agent': '母', 'place': '山頂'}, ['母', '山頂'], 'agent:が + place:で:PLACE')
    R(t, '警官が交差点で笑った。', '笑う', {'agent': '警官', 'place': '交差点'}, ['警官', '交差点'], 'agent:が + place:で:PLACE')
    R(t, '兵士が国道で驚いた。', '驚く', {'agent': '兵士', 'place': '国道'}, ['兵士', '国道'], 'agent:が + place:で:PLACE')
    R(t, '村人が農道で驚かなかった。', '驚く', {'agent': '村人', 'place': '農道'}, ['村人', '農道'], 'agent:が + place:で:PLACE(否定)')
    R(t, '選手が土俵で喜んだ。', '喜ぶ', {'agent': '選手', 'place': '土俵'}, ['選手', '土俵'], 'agent:が + place:で:PLACE')
    R(t, 'チームが校庭で喜んだ。', '喜ぶ', {'agent': 'チーム', 'place': '校庭'}, ['チーム', '校庭'], 'agent:が:GROUP_ORG + place:で:PLACE')
    R(t, '花子が校庭で笑った。', '笑う', {'agent': '花子', 'place': '校庭'}, ['花子', '校庭'], 'agent:が:MULTIPLE(全候補が合う: ANIMAL+PERSON)')
    R(t, '政府が国道で怒った。', '怒る', {'agent': '政府', 'place': '国道'}, ['政府', '国道'], 'agent:が:GROUP_ORG + place:で:PLACE')
    R(t, '警察が校庭で怒った。', '怒る', {'agent': '警察', 'place': '校庭'}, ['警察', '校庭'], 'agent:が:MULTIPLE(全候補が合う: GROUP_ORG+PERSON)')
    R(t, '兄が校庭で試合を楽しんだ。', '楽しむ', {'agent': '兄', 'place': '校庭', 'patient': '試合'}, ['兄', '校庭', '試合'], 'agent:が + place:で + patient:を:EVENT_ACT')
    R(t, '弟が森林で歌を楽しんだ。', '楽しむ', {'agent': '弟', 'place': '森林', 'patient': '歌'}, ['弟', '森林', '歌'], 'patient:を:WORK')
    R(t, '姉が湖で音楽を楽しむ。', '楽しむ', {'agent': '姉', 'place': '湖', 'patient': '音楽'}, ['姉', '湖', '音楽'], 'patient:を:WORK(非過去)')
    R(t, '母が神社で歌を好んだ。', '好む', {'agent': '母', 'place': '神社', 'patient': '歌'}, ['母', '神社', '歌'], 'patient:を:WORK')
    R(t, '祖父が山頂で酒を好んだ。', '好む', {'agent': '祖父', 'place': '山頂', 'patient': '酒'}, ['祖父', '山頂', '酒'], 'patient:を:SUBSTANCE_FOOD')
    R(t, '兄が校庭で弟を笑った。', '笑う', {'agent': '兄', 'place': '校庭', 'patient': '弟'}, ['兄', '校庭', '弟'], 'patient:を:PERSON')
    R(t, '先生が校庭で生徒を笑わなかった。', '笑う', {'agent': '先生', 'place': '校庭', 'patient': '生徒'}, ['先生', '校庭', '生徒'], 'patient:を:PERSON(否定)')
    R(t, '兄が校庭で喧嘩を楽しんだ。', '楽しむ', {'agent': '兄', 'place': '校庭', 'patient': '喧嘩'}, ['兄', '校庭', '喧嘩'], 'patient:を:EVENT_ACT')
    R(t, '父が国道で約束を喜んだ。', '喜ぶ', {'agent': '父', 'place': '国道', 'patient': '約束'}, ['父', '国道', '約束'], 'patient:を:EVENT_ACT')
    R(t, '弟が校庭で絵を好んだ。', '好む', {'agent': '弟', 'place': '校庭', 'patient': '絵'}, ['弟', '校庭', '絵'], 'patient:を:WORK')
    R(t, '兄が町の校庭で泣いた。', '泣く', {'agent': '兄', 'place': '町の校庭'}, ['兄', '校庭'], 'place:で:の(主辞 PLACE)')
    R(t, '兄が校庭で手紙を喜んだ。', '喜ぶ', {'agent': '兄', 'place': '校庭', 'patient': '手紙'}, ['兄', '校庭', '手紙'], 'patient:を:MULTIPLE(全候補が合う: ABSTRACT+IDENTIFIER+INFO_LANGUAGE+WORK)')
    R(t, '母が校庭で絵本を楽しんだ。', '楽しむ', {'agent': '母', 'place': '校庭', 'patient': '絵本'}, ['母', '校庭', '絵本'], 'patient:を:MULTIPLE(全候補が合う: ARTIFACT+INFO_LANGUAGE+WORK)')
    # ---- abstain ----------------------------------------------------------------------------------------------------------------------------------------------------
    A(t, '兄が風に驚いた。', '驚く', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_EMOTION:に', ['兄', '風'], '(c) に(cause): 原因か相手か。規約が型を決めない')
    A(t, '弟が雨に喜んだ。', '喜ぶ', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_EMOTION:に', ['弟', '雨'], '(c) に(cause)')
    A(t, '姉が雪に驚いた。', '驚く', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_EMOTION:に', ['姉', '雪'], '(c) に(cause)')
    A(t, '兄が弟に怒った。', '怒る', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_EMOTION:に', ['兄', '弟'], '(c) に+人(相手。cause か addressee か)')
    A(t, '母が先生に怒った。', '怒る', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_EMOTION:に', ['母', '先生'], '(c) に+人(相手)')
    A(t, '兄が休日に校庭で喜んだ。', '喜ぶ', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_EMOTION:に', ['兄', '休日', '校庭'], '(c) に+TIME(原因か時か。表に time の行が無い)')
    A(t, '弟が校庭で屋根から笑った。', '笑う', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_EMOTION:から', ['弟', '校庭', '屋根'], '(c) から: 表に行が無い')
    A(t, '兄が畑へ泣いた。', '泣く', 'PLACEMENT_PARTICLE_NOT_IN_FRAME:P_EMOTION:へ', ['兄', '畑'], '(c) へ: 表に行が無い')
    A(t, '兄が試合で喜んだ。', '喜ぶ', 'PLACEMENT_TYPE_MISMATCH:P_EMOTION:で:EVENT_ACT', ['兄', '試合'], '(a) で: 原因(EVENT_ACT)か場所か。表の place は PLACE だけ')
    A(t, '弟が喧嘩で泣いた。', '泣く', 'PLACEMENT_TYPE_MISMATCH:P_EMOTION:で:EVENT_ACT', ['弟', '喧嘩'], '(a) で: 原因か場所か')
    A(t, '母が約束で喜んだ。', '喜ぶ', 'PLACEMENT_TYPE_MISMATCH:P_EMOTION:で:EVENT_ACT', ['母', '約束'], '(a) で: 原因か場所か')
    A(t, '兄が野球で喜んだ。', '喜ぶ', 'PLACEMENT_MULTIPLE:で:野球', ['兄', '野球'], '(a) で: MULTIPLE(EVENT_ACT+PLACE+WORK: 原因か場所か)')
    A(t, '姉が勝利で泣いた。', '泣く', 'PLACEMENT_MULTIPLE:で:勝利', ['姉', '勝利'], '(a) で: MULTIPLE(EVENT_ACT+PLACE+TIME: 原因か場所か時か)')
    A(t, '機械が校庭で笑った。', '笑う', 'PLACEMENT_TYPE_MISMATCH:P_EMOTION:が:ARTIFACT', ['機械', '校庭'], 'agent:が:ARTIFACT')
    A(t, '風が森林で笑った。', '笑う', 'PLACEMENT_TYPE_MISMATCH:P_EMOTION:が:NATURAL_PHENOMENON', ['風', '森林'], 'agent:が:NATURAL_PHENOMENON')
    A(t, '客が校庭で泣いた。', '泣く', 'PLACEMENT_MULTIPLE:が:客', ['客', '校庭'], '(b) agent:が:MULTIPLE(NATURAL_PHENOMENON+PERSON)')
    A(t, '医者が国道で笑った。', '笑う', 'PLACEMENT_MULTIPLE:が:医者', ['医者', '国道'], '(b) agent:が:MULTIPLE(PERSON+PLACE)')
    A(t, '伊藤が校庭で泣いた。', '泣く', 'PLACEMENT_UNPLACED:が:伊藤', ['伊藤', '校庭'], 'agent:が:UNPLACED(固有名)', roles={'agent': '伊藤', 'place': '校庭'})
    A(t, '加藤が国道で笑った。', '笑う', 'PLACEMENT_UNPLACED:が:加藤', ['加藤', '国道'], 'agent:が:UNPLACED(固有名)', roles={'agent': '加藤', 'place': '国道'})
    A(t, '兄が書斎で泣いた。', '泣く', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:書斎', ['兄', '書斎'], '(e) place:で:PLACE だが腕が role@ だけ(付加の門 5)', roles={'agent': '兄', 'place': '書斎'})
    A(t, '母が廊下で笑った。', '笑う', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:廊下', ['母', '廊下'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '母', 'place': '廊下'})
    A(t, '弟が縁側で驚いた。', '驚く', 'PLACEMENT_SLOT_EVIDENCE_ONLY:で:縁側', ['弟', '縁側'], '(e) place:で:PLACE だが腕が role@ だけ', roles={'agent': '弟', 'place': '縁側'})
    A(t, '兄が街角で泣いた。', '泣く', 'PLACEMENT_MULTIPLE:で:街角', ['兄', '街角'], '(b) place:で:MULTIPLE(PLACE+WORK)')
    A(t, '兄が国道で湖を楽しんだ。', '楽しむ', 'PLACEMENT_TYPE_MISMATCH:P_EMOTION:を:PLACE', ['兄', '国道', '湖'], '(c) を+PLACE(対象。patient は PLACE を除く)', roles={'agent': '兄', 'place': '国道', 'patient': '湖'})
    A(t, '弟が校庭で川を好んだ。', '好む', 'PLACEMENT_TYPE_MISMATCH:P_EMOTION:を:PLACE', ['弟', '校庭', '川'], '(c) を+PLACE', roles={'agent': '弟', 'place': '校庭', 'patient': '川'})
    A(t, '弟が校庭で水を好んだ。', '好む', 'PLACEMENT_MULTIPLE:を:水', ['弟', '校庭', '水'], '(b) patient:を:MULTIPLE(SUBSTANCE_FOOD+TIME)', roles={'agent': '弟', 'place': '校庭', 'patient': '水'})
    A(t, '母が校庭で話を楽しんだ。', '楽しむ', 'PLACEMENT_UNPLACED:を:話', ['母', '校庭', '話'], 'patient:を:UNPLACED', roles={'agent': '母', 'place': '校庭', 'patient': '話'})
    A(t, '兄が校庭で歴史を楽しんだ。', '楽しむ', 'PLACEMENT_ESTIMATED_GENERATED:を:歴史', ['兄', '校庭', '歴史'], '(e) patient:を:推定(生成)', roles={'agent': '兄', 'place': '校庭', 'patient': '歴史'})
    A(t, '子供が校庭で泣いた。', '泣く', 'PLACEMENT_DIRECT_VIA_GENERATED:が:子供', ['子供', '校庭'], '(e) agent:が:PERSON だが決め手に生成の腕', roles={'agent': '子供', 'place': '校庭'})
    A(t, '兄があまり校庭で泣かなかった。', '泣く', 'NT', ['兄', '校庭'], '(d) 否定の中の副詞(あまり + ない)')
    A(t, '兄が全然国道で笑わなかった。', '笑う', 'NT', ['兄', '国道'], '(d) 否定の中の副詞(全然 + ない)')
    A(t, '兄が校庭で弟と笑った。', '笑う', 'NT', ['兄', '校庭', '弟'], '(d) と(companion。6 つの助詞の外)', roles={'agent': '兄', 'place': '校庭', 'companion': '弟'})
    A(t, '兄が弟を呼んで、校庭で笑った。', '笑う', 'NT', ['兄', '弟', '校庭'], '(d) 目的語・主語の省略(2 節の文)')
    A(t, '兄が校庭で慌てた。', '慌てる', 'PLACEMENT_PREDICATE_POSSIBLY_DERIVED', ['兄', '校庭'], '(e) 派生の門(下一段の述語)', roles={'agent': '兄', 'place': '校庭'})
    A(t, '兄が国道で疲れた。', '疲れる', 'PLACEMENT_PREDICATE_POSSIBLY_DERIVED', ['兄', '国道'], '(e) 派生の門(下一段の述語)', roles={'agent': '兄', 'place': '国道'})
    A(t, '兄が校庭で泣いている。', '泣く', 'PLACEMENT_PREDICATE_TAIL_UNINTERPRETED', ['兄', '校庭'], '(e) 語尾の門(ている)')
    A(t, '兄が校庭で泣かされた。', '泣く', 'PLACEMENT_VOICE_NOT_ACTIVE', ['兄', '校庭'], '(e) 態(使役受身)')


def unread():
    # a type whose predicate the table does not read: the plan stops at the type of the predicate (the filler types are all fine, so only the type of the predicate is the reason)
    X('GIVE', '兄が校庭で本を買った。', '買う', 'PLACEMENT_FRAME_NOT_READ:P_GIVE', ['兄', '校庭', '本'], 'P_GIVE: が・に の人が与え手か受け手か')
    X('GIVE', '弟が国道で本を買った。', '買う', 'PLACEMENT_FRAME_NOT_READ:P_GIVE', ['弟', '国道', '本'], 'P_GIVE')
    X('GIVE', '姉が森林で荷車を出した。', '出す', 'PLACEMENT_FRAME_NOT_READ:P_GIVE', ['姉', '森林', '荷車'], 'P_GIVE')
    X('GIVE', '母が校庭で皿を買った。', '買う', 'PLACEMENT_FRAME_NOT_READ:P_GIVE', ['母', '校庭', '皿'], 'P_GIVE')
    X('PERCEIVE', '兄が校庭で鳥を見た。', '見る', 'PLACEMENT_FRAME_NOT_READ:P_PERCEIVE', ['兄', '校庭', '鳥'], 'P_PERCEIVE: が の人が知覚する側かされる側か')
    X('PERCEIVE', '弟が森林で鳥を探した。', '探す', 'PLACEMENT_FRAME_NOT_READ:P_PERCEIVE', ['弟', '森林', '鳥'], 'P_PERCEIVE')
    X('PERCEIVE', '姉が山頂で鳥を探した。', '探す', 'PLACEMENT_FRAME_NOT_READ:P_PERCEIVE', ['姉', '山頂', '鳥'], 'P_PERCEIVE')
    X('PERCEIVE', '母が湖で魚を見た。', '見る', 'PLACEMENT_FRAME_NOT_READ:P_PERCEIVE', ['母', '湖', '魚'], 'P_PERCEIVE')
    X('EXIST', '兄が校庭で休んだ。', '休む', 'PLACEMENT_FRAME_NOT_READ:P_EXIST', ['兄', '校庭'], 'P_EXIST: が が entity か agent か')
    X('EXIST', '弟が森林で待った。', '待つ', 'PLACEMENT_FRAME_NOT_READ:P_EXIST', ['弟', '森林'], 'P_EXIST')
    X('EXIST', '姉が歩道で座った。', '座る', 'PLACEMENT_FRAME_NOT_READ:P_EXIST', ['姉', '歩道'], 'P_EXIST')
    X('EXIST', '祖父が神社で泊まった。', '泊まる', 'PLACEMENT_FRAME_NOT_READ:P_EXIST', ['祖父', '神社'], 'P_EXIST')
    X('POSSESS', '兄が校庭で財布を拾った。', '拾う', 'PLACEMENT_FRAME_NOT_READ:P_POSSESS', ['兄', '校庭', '財布'], 'P_POSSESS: が が agent か recipient か')
    X('POSSESS', '弟が国道で財布を取った。', '取る', 'PLACEMENT_FRAME_NOT_READ:P_POSSESS', ['弟', '国道', '財布'], 'P_POSSESS')
    X('POSSESS', '母が湖で箱を握った。', '握る', 'PLACEMENT_FRAME_NOT_READ:P_POSSESS', ['母', '湖', '箱'], 'P_POSSESS')
    X('POSSESS', '兄が校庭で財布を失った。', '失う', 'PLACEMENT_FRAME_NOT_READ:P_POSSESS', ['兄', '校庭', '財布'], 'P_POSSESS')
    X('STATE', '兄が校庭で忙しかった。', '忙しい', 'NT', ['兄', '校庭'], 'P_STATE: 形容詞の述語')
    X('STATE', '弟が森林で美しかった。', '美しい', 'NT', ['弟', '森林'], 'P_STATE')
    X('STATE', '姉が歩道で忙しくなかった。', '忙しい', 'NT', ['姉', '歩道'], 'P_STATE(否定)')
    X('COGNITION', '兄が校庭で歌を学んだ。', '学ぶ', 'PLACEMENT_FRAME_NOT_READ:P_COGNITION', ['兄', '校庭', '歌'], 'P_COGNITION: が が対象か agent か。に・と が決まらない')
    X('COGNITION', '弟が森林で規則を学んだ。', '学ぶ', 'PLACEMENT_FRAME_NOT_READ:P_COGNITION', ['弟', '森林', '規則'], 'P_COGNITION')
    X('COGNITION', '姉が山頂で歌を知った。', '知る', 'PLACEMENT_FRAME_NOT_READ:P_COGNITION', ['姉', '山頂', '歌'], 'P_COGNITION')
    X('COGNITION', '母が神社で約束を思った。', '思う', 'PLACEMENT_FRAME_NOT_READ:P_COGNITION', ['母', '神社', '約束'], 'P_COGNITION')


def build():
    act()
    change()
    create()
    consume()
    emotion()
    unread()
