"""The operator's guide, generated from the registry rather than written.

A hand-written wiki and the software it documents drift apart the first time
someone renames a field in a hurry, and nothing fails when they do — the wiki
just quietly starts lying. Here the guide has no independent content: every
line comes from `settings_registry`, which `verify_against_source()` checks
against the actual Swift tree. A stale guide therefore shows up as a failing
check rather than as a confused user.

Two audiences, one source:

    render_guide()      the full reference — every setting, every mode
    render_quickstart() the short path for someone opening the app today

The mode section is the reason this exists at all. The IDE has six families
of modes living on five different screens, so a reader meets each one alone
and cannot tell which switch governs what. Printed together, with "when you
would pick this" on every option, they become a decision table.

Japanese and English are emitted side by side rather than as two documents,
because two documents is how one of them ends up out of date.
"""
from __future__ import annotations

from typing import List

from .settings_registry import (MODE_FAMILIES, SETTINGS, TABS, ModeFamily,
                                Setting, verify_against_source)


def _setting_row(s: Setting) -> str:
    cli = f"`{s.cli}`" if s.cli else "— (GUI only)"
    values = ", ".join(f"`{v}`" for v in s.values) if s.values else "free-form"
    return (f"| {s.title_en}<br>{s.title_ja} | Settings › {s.tab} | "
            f"{s.what} | {values} | {cli} |")


def _mode_section(f: ModeFamily) -> List[str]:
    out = [
        f"### {f.title_en} / {f.title_ja}",
        "",
        f"{f.what}",
        "",
        f"Where: **Settings › {f.tab}**  ·  Source: `{f.source}`",
        "",
        "| Option | What it does | When to pick it |",
        "|---|---|---|",
    ]
    for o in f.options:
        out.append(f"| **{o.label_en}** / {o.label_ja} | {o.what} | {o.when} |")
    out.append("")
    return out


def render_guide(source_root: str = "") -> str:
    """Full reference. Pass the IDE checkout to stamp a freshness line."""
    out: List[str] = [
        "# Verantyx — Settings and Modes",
        "",
        "Generated from `verantyx/settings_registry.py`. Do not edit this file "
        "by hand: it is overwritten, and the registry is the thing that is "
        "checked against the source.",
        "",
    ]

    if source_root:
        fresh = verify_against_source(source_root)
        if fresh["verdict"] == "ANSWER":
            out += [f"> Verified against {fresh['swift_files']} Swift files: "
                    f"all {fresh['checked_settings']} settings keys and "
                    f"{fresh['checked_mode_families']} mode families still exist.", ""]
        elif fresh["verdict"] == "UNKNOWN_NO_SOURCE":
            out += ["> **Not verified** — the IDE source was not available when "
                    "this was generated, so nothing here was re-checked.", ""]
        else:
            out += [f"> **Stale** — these no longer exist in the source: "
                    f"{fresh['missing_defaults_keys']} "
                    f"{fresh['missing_mode_sources']}", ""]

    out += [
        "## Modes",
        "",
        "Six independent families. They are listed together because each one "
        "appears alone in the interface, which makes every switch look like "
        "*the* mode switch; knowing which family a setting belongs to tells "
        "you what it cannot affect.",
        "",
    ]
    for fam in MODE_FAMILIES:
        out += _mode_section(fam)

    out += ["## Settings", ""]
    for tab in TABS:
        rows = [s for s in SETTINGS if s.tab == tab]
        if not rows:
            continue
        out += [f"### Settings › {tab}", "",
                "| Setting | Where | What it does | Values | CLI |",
                "|---|---|---|---|---|"]
        out += [_setting_row(s) for s in rows]
        out.append("")

    gui_only = sum(1 for s in SETTINGS if s.cli is None)
    out += [
        "## On the CLI column",
        "",
        f"{gui_only} of {len(SETTINGS)} settings are GUI-only, and the table "
        "says so rather than leaving the column blank. The support bot returns "
        "`UNKNOWN_NO_CLI` for these — an answer you can act on, unlike a "
        "plausible-looking command that does not exist.",
        "",
    ]
    return "\n".join(out)


def render_quickstart() -> str:
    """The short path: what to set before doing anything else."""
    firsts = ["language", "model.ollama", "model.ollama_endpoint",
              "api.anthropic", "agent.loop"]
    by_key = {s.key: s for s in SETTINGS}
    out = [
        "# Verantyx — Quick start",
        "",
        "Five settings decide how the app behaves. Everything else can wait.",
        "",
    ]
    for i, key in enumerate(firsts, start=1):
        s = by_key.get(key)
        if s is None:
            continue
        out += [f"{i}. **{s.title_en} / {s.title_ja}** — {s.what}",
                f"   Settings › {s.tab} › {s.title_en}", ""]
    out += [
        "Then pick two modes:",
        "",
    ]
    for group in ("operation", "inference"):
        fam = next((f for f in MODE_FAMILIES if f.group == group), None)
        if fam is None:
            continue
        out += [f"- **{fam.title_en} / {fam.title_ja}** ({fam.what})"]
        for o in fam.options:
            out.append(f"  - `{o.label_en}` — {o.when}")
        out.append("")
    out += [
        "Stuck? Ask the support bot in the app. It answers from this same "
        "registry, so it will tell you a setting does not exist rather than "
        "inventing where it lives.",
        "",
    ]
    return "\n".join(out)
